###############################################################################
#
# signature.b64sig -- 9920868842008fc9
#
# TH8 Script Signature File (Harpy)
#
###############################################################################

  GinPpA+w/SbfNIYfpLjYa3cs8sQFPG7BBIamSmHNaQfFrJSO6b2Sw1U02xptvwv5BJ3kGIb+jMvb
  tpqsUSHpqpD1tBvixKmf4vmQW7XhqQneRtkiYKDHM2l2IGc4jRiaXtNg6dl0cVu8u1Y2Y4opqFkM
  y95x8j28NnKqBMFAq4HY9Tin+Ovwyf/vqxjHOBMS2AvDa79F8M9HZcG4JBs5gNo1eMM5CQaIAYB5
  nsduRT0nawUgz3yYRg6t3ts8Boq1wawx+5IjjFtKiOl9l9sryMQyxNEUb5MCA1Rhy+0FAdchc8Kj
  HZIfZdy05dh2byVOaiPAW1khsHa18P8r7iAdlQ==
