#!/usr/bin/env tclsh
###############################################################################
#
# mkkey.tcl --
#
#     Embedded key generator for TH8.
#
#     Two output modes:
#
#       SINGLE-KEY MODE (default):
#         Reads a binary SNK file and produces a C source file with the
#         key data as a static const unsigned char array plus an
#         accessor `Th8_GetEmbedded<Name>()`.
#
#         Usage:
#             tclsh tools/mkkey.tcl <keyFile.snk>
#
#         Output: src/plugins/harpy/th8_<baseName>.c
#
#       KEYRING MODE (--keyring):
#         Reads N binary SNK files and produces a single C source file
#         that defines `Th8_GetEmbeddedKeyring()`, the embedder-supplied
#         trust-anchor collection consumed by signed-only callers.
#         The generated file MUST be linked instead of (or in addition
#         to, with TH8_OMIT_KEYRING_STUB defined) the canonical
#         th8_keyring_stub.c.
#
#         Usage:
#             tclsh tools/mkkey.tcl --keyring [-o OUTPATH] <k1.snk> [k2.snk ...]
#
#         Output (default): src/plugins/harpy/th8_keyring.c
#
# Copyright (c) 2026 by Joe Mistachkin.  All rights reserved.
#
# See the file "license.terms" for information on usage and redistribution of
# this file, and for a DISCLAIMER OF ALL WARRANTIES.
#
###############################################################################


###############################################################################
#
# formatHexArray --
#
#     Format binary data as a C array initializer with 12 hex bytes
#     per line, indented with 4 spaces.
#
###############################################################################

proc formatHexArray {data} {
  set len [string length $data]
  set lines {}
  set line "    "
  set col 0

  for {set i 0} {$i < $len} {incr i} {
    set byte [scan [string index $data $i] %c]
    set hex [format "0x%02x" $byte]

    if {$i < $len - 1} then {
      append hex ","
    }

    if {$col > 0} then {
      append line " "
    }
    append line $hex
    incr col

    if {$col >= 12 && $i < $len - 1} then {
      lappend lines $line
      set line "    "
      set col 0
    }
  }

  #
  # Flush the last partial line.
  #
  if {$col > 0} then {
    lappend lines $line
  }

  return [join $lines "\n"]
}


###############################################################################
#
# capitalizeFirst --
#
#     Capitalize the first letter of a string without disturbing
#     the rest.
#
###############################################################################

proc capitalizeFirst {s} {
  return [string toupper [string index $s 0]][string range $s 1 end]
}


###############################################################################
#
# readBinaryFile --
#
#     Read a file in binary mode and return its raw bytes.
#
###############################################################################

proc readBinaryFile {path} {
  set fd [open $path rb]
  set data [read $fd]
  close $fd
  return $data
}


###############################################################################
#
# generateSingleKey --
#
#     Emit a single-key C source file (legacy mkkey behaviour).
#
###############################################################################

proc generateSingleKey {snkPath projectRoot} {
  if {![file exists $snkPath]} then {
    puts stderr "Error: file not found: $snkPath"
    exit 1
  }

  #
  # Derive the base name from the input file (e.g., "key0" from
  # "key0.snk").
  #
  set baseName [file rootname [file tail $snkPath]]

  set data [readBinaryFile $snkPath]
  set len  [string length $data]

  set varPrefix  "th8_${baseName}"
  set funcSuffix [capitalizeFirst $baseName]
  set funcName   "Th8_GetEmbedded${funcSuffix}"

  set outDir  [file join $projectRoot src plugins harpy]
  set outPath [file join $outDir "th8_${baseName}.c"]

  file mkdir $outDir

  set hexBody [formatHexArray $data]

  set out ""
  append out "/*\n"
  append out " * th8_${baseName}.c -- Embedded public key \"${baseName}\".\n"
  append out " *\n"
  append out " * Auto-generated by tools/mkkey.tcl.  DO NOT EDIT BY HAND.\n"
  append out " *\n"
  append out " * Copyright (c) 2026 by Joe Mistachkin.  All rights reserved.\n"
  append out " *\n"
  append out " * See the file \"license.terms\" for information on usage and redistribution of\n"
  append out " * this file, and for a DISCLAIMER OF ALL WARRANTIES.\n"
  append out " */\n"
  append out "\n"
  append out "#include \"th8.h\"\n"
  append out "\n"
  append out "#if defined(TH8_ENABLE_CRYPTOGRAPHY)\n"
  append out "\n"
  append out "static const unsigned char ${varPrefix}_data\[\] = \{\n"
  append out "${hexBody}\n"
  append out "\};\n"
  append out "\n"
  append out "static const size_t ${varPrefix}_size = sizeof(${varPrefix}_data);\n"
  append out "\n"
  append out "/*\n"
  append out " * ${funcName} --\n"
  append out " *    Returns a pointer to the embedded ${baseName} data and its size.\n"
  append out " */\n"
  append out "const unsigned char *\n"
  append out "${funcName}(size_t *pnData)\n"
  append out "\{\n"
  append out "    if (pnData) *pnData = ${varPrefix}_size;\n"
  append out "    return ${varPrefix}_data;\n"
  append out "\}\n"
  append out "\n"
  append out "#endif /* TH8_ENABLE_CRYPTOGRAPHY */\n"

  set fd [open $outPath w]
  fconfigure $fd -encoding binary -translation binary
  puts -nonewline $fd $out
  close $fd

  puts "Generated $outPath ($len bytes embedded)"
}


###############################################################################
#
# generateKeyring --
#
#     Emit a single C source file defining Th8_GetEmbeddedKeyring()
#     over `snkPaths`.  The output path defaults to
#     src/plugins/harpy/th8_keyring.c but the caller may override it
#     so the file lands in an embedder-controlled directory (e.g.,
#     Ladybird's Libraries/LibTH8/Vendor/).
#
###############################################################################

proc generateKeyring {snkPaths outPath} {
  set nEntries [llength $snkPaths]
  if {$nEntries == 0} then {
    puts stderr "Error: --keyring requires at least one .snk file"
    exit 1
  }

  #
  # Read every SNK first so we fail before truncating the output on
  # a missing file.
  #
  set blobs {}
  foreach snkPath $snkPaths {
    if {![file exists $snkPath]} then {
      puts stderr "Error: file not found: $snkPath"
      exit 1
    }
    lappend blobs [list [file tail $snkPath] [readBinaryFile $snkPath]]
  }

  #
  # Ensure the output directory exists.
  #
  file mkdir [file dirname $outPath]

  set out ""
  append out "/*\n"
  append out " * th8_keyring.c -- Embedded trusted-root keyring.\n"
  append out " *\n"
  append out " * Auto-generated by tools/mkkey.tcl --keyring.  DO NOT EDIT BY HAND.\n"
  append out " *\n"
  append out " * Source SNK files (in order):\n"
  foreach blob $blobs {
    lassign $blob name data
    append out " *   $name ([string length $data] bytes)\n"
  }
  append out " *\n"
  append out " * This translation unit defines Th8_GetEmbeddedKeyring() with a\n"
  append out " * strong symbol.  Link it INSTEAD of th8_keyring_stub.c, or compile\n"
  append out " * the stub with -DTH8_OMIT_KEYRING_STUB so its definition is\n"
  append out " * elided and this one wins at link time.\n"
  append out " *\n"
  append out " * Copyright (c) 2026 by Joe Mistachkin.  All rights reserved.\n"
  append out " *\n"
  append out " * See the file \"license.terms\" for information on usage and redistribution of\n"
  append out " * this file, and for a DISCLAIMER OF ALL WARRANTIES.\n"
  append out " */\n"
  append out "\n"
  append out "#include \"th8.h\"\n"
  append out "\n"
  append out "#if defined(TH8_ENABLE_CRYPTOGRAPHY)\n"
  append out "\n"

  set idx 0
  foreach blob $blobs {
    lassign $blob name data
    set hexBody [formatHexArray $data]
    append out "/* Entry ${idx}: ${name} ([string length $data] bytes). */\n"
    append out "static const unsigned char th8_keyring_data_${idx}\[\] = \{\n"
    append out "${hexBody}\n"
    append out "\};\n"
    append out "\n"
    incr idx
  }

  append out "static const Th8_KeyringEntry th8_keyring_entries\[\] = \{\n"
  for {set i 0} {$i < $nEntries} {incr i} {
    append out "    { th8_keyring_data_${i}, sizeof(th8_keyring_data_${i}) },\n"
  }
  append out "\};\n"
  append out "\n"
  append out "/*\n"
  append out " * Th8_GetEmbeddedKeyring --\n"
  append out " *    Strong override of the th8_keyring_stub.c symbol.\n"
  append out " *    Returns the populated array of trusted-root keys.\n"
  append out " */\n"
  append out "const Th8_KeyringEntry *\n"
  append out "Th8_GetEmbeddedKeyring(size_t *pnEntries)\n"
  append out "\{\n"
  append out "    if (pnEntries) *pnEntries = sizeof(th8_keyring_entries) /\n"
  append out "                                sizeof(th8_keyring_entries\[0\]);\n"
  append out "    return th8_keyring_entries;\n"
  append out "\}\n"
  append out "\n"
  append out "#endif /* TH8_ENABLE_CRYPTOGRAPHY */\n"

  set fd [open $outPath w]
  fconfigure $fd -encoding binary -translation binary
  puts -nonewline $fd $out
  close $fd

  puts "Generated $outPath (${nEntries} entries embedded)"
}


###############################################################################
#
# usage --
#
###############################################################################

proc usage {} {
  puts stderr "Usage: tclsh tools/mkkey.tcl <keyFile.snk>"
  puts stderr "       tclsh tools/mkkey.tcl --keyring \[-o OUTPATH\] <k1.snk> \[k2.snk ...\]"
  exit 1
}


###############################################################################
#
# main --
#
#     Entry point.  Dispatches between single-key and keyring modes
#     based on the leading --keyring flag.
#
###############################################################################

proc main {argv} {
  set scriptDir   [file dirname [info script]]
  set projectRoot [file dirname $scriptDir]

  if {[llength $argv] < 1} then {
    usage
  }

  set first [lindex $argv 0]

  if {$first eq "--keyring"} then {
    set rest [lrange $argv 1 end]
    set outPath [file join $projectRoot src plugins harpy th8_keyring.c]

    while {[llength $rest] > 0 && [string match "-*" [lindex $rest 0]]} {
      set flag [lindex $rest 0]
      switch -- $flag {
        "-o" {
          if {[llength $rest] < 2} then {
            puts stderr "Error: -o requires a path argument"
            exit 1
          }
          set outPath [lindex $rest 1]
          set rest [lrange $rest 2 end]
        }
        default {
          puts stderr "Error: unknown flag: $flag"
          usage
        }
      }
    }

    generateKeyring $rest $outPath
    return
  }

  if {[llength $argv] != 1} then {
    usage
  }

  generateSingleKey $first $projectRoot
}

main $argv
