#!/usr/bin/env tclsh
###############################################################################
#
# mkversion.tcl --
#
# Generates th8_version_gen.h from Fossil or Git checkout metadata.
# Cross-platform replacement for the shell script in the Makefile.
#
# Usage:
#   tclsh tools/mkversion.tcl ?OUTPUT_FILE?
#
# If OUTPUT_FILE is omitted, defaults to bin/th8_version_gen.h.
# The file is only rewritten if its content would change (to avoid
# unnecessary recompilation).
#
# Copyright (c) 2026 by Joe Mistachkin.  All rights reserved.
#
# See the file "license.terms" for information on usage and redistribution of
# this file, and for a DISCLAIMER OF ALL WARRANTIES.
#
###############################################################################

proc main {args} {
  #
  # Determine output path.
  #

  if {[llength $args] > 0} then {
    set outFile [lindex $args 0]
  } else {
    set outFile [file join bin th8_version_gen.h]
  }

  #
  # Detect VCS and extract metadata.
  #

  set srcId       "unknown"
  set srcDatetime "unknown"
  set srcTags     "unknown"
  set srcVcs      "none"

  if {![catch {exec fossil info} info] && \
      [string match "*\ncheckout:*" "\n$info"]} then {
    #
    # Fossil checkout.  NOTE: `fossil info` exits 0 even OUTSIDE any open
    # checkout (it then reports only the global ~/.fossil config-db), so a
    # zero exit is NOT proof of a checkout.  Require an actual "checkout:"
    # line before trusting this branch; otherwise fall through to the git
    # probe below.  Without this guard, a git checkout that happens to have
    # a global fossil config-db (e.g. the git mirror of this Fossil repo)
    # takes this branch, finds no "checkout:"/"tags:" lines, and stamps the
    # source id/timestamp/tags as "unknown" -- silently losing provenance in
    # the generated amalgamation (Bug 83).
    #

    set srcVcs "Fossil"
    foreach line [split $info \n] {
      if {[string match "checkout:*" $line]} then {
        set parts [split [string trim \
            [string range $line 9 end]]]
        if {[llength $parts] >= 1} then {
          set srcId [string range [lindex $parts 0] 0 15]
        }
        if {[llength $parts] >= 3} then {
          set srcDatetime "[lindex $parts 1] [lindex $parts 2]"
        }
      }
      if {[string match "tags:*" $line]} then {
        set srcTags [string trim [string range $line 5 end]]
      }
    }
  } elseif {![catch {exec git rev-parse --git-dir} _]} then {
    #
    # Git checkout.
    #

    set srcVcs "Git"
    catch {
      set srcId [string range \
          [exec git rev-parse HEAD] 0 15]
    }
    catch {
      set dt [exec git log -1 --format=%ci]
      set srcDatetime [string range $dt 0 18]
    }
    catch {
      set srcTags [exec git describe --tags --always]
    }
  }

  #
  # Generate the header content.
  #

  #
  # Read the VERSION file if it exists (one line, e.g. "1.0.0").
  #

  set patchLevel "0.0.0"
  set versionFile [file join [file dirname [file dirname \
      [file normalize [info script]]]] VERSION]
  if {[file exists $versionFile]} then {
    set fd [open $versionFile r]
    set patchLevel [string trim [read $fd]]
    close $fd
  }
  set version [join [lrange [split $patchLevel .] 0 1] .]; # X.Y.Z => X.Y

  #
  # Derive the Win32 4-component version forms from the patchLevel.
  # Win32 VERSIONINFO requires both a comma-separated tuple
  # (FILEVERSION / PRODUCTVERSION) and a dotted-token form (used
  # via STRINGIFY for the FileVersion / ProductVersion strings).
  # Both are 4 components -- if VERSION has fewer, pad with zeros;
  # if it has more, truncate.
  #
  # Examples:
  #   "1.0.0"       -> rcVersion="1,0,0,0",  patchLevelToken="1.0.0.0"
  #   "1.0"         -> rcVersion="1,0,0,0",  patchLevelToken="1.0.0.0"
  #   "2.5.1.42"    -> rcVersion="2,5,1,42", patchLevelToken="2.5.1.42"
  #
  # Non-numeric components in VERSION (alpha, beta, etc) are NOT
  # supported here -- VERSIONINFO requires WORDs.  If the VERSION
  # file ever grows pre-release suffixes the resource version
  # would need to ignore them; for now, the format is plain
  # dotted-numeric and that matches the file.
  #
  set parts [split $patchLevel .]
  while {[llength $parts] < 4} {
    lappend parts 0
  }
  set parts [lrange $parts 0 3]
  set rcVersionTuple [join $parts ,]
  set rcPatchLevelToken [join $parts .]

  #
  # Generate the header content.
  #

  set content ""
  append content "/*\n"
  append content " * th8_version_gen.h --\n"
  append content " *\n"
  append content " *\tAuto-generated by mkversion.tcl.  DO NOT EDIT BY HAND.\n"
  append content " *\n"
  append content " * Copyright (c) 2026 by Joe Mistachkin.  All rights reserved.\n"
  append content " *\n"
  append content " * See the file \"license.terms\" for information on usage and redistribution of\n"
  append content " * this file, and for a DISCLAIMER OF ALL WARRANTIES.\n"
  append content " */\n"
  append content "\n"
  append content "#ifndef TH8_VERSION_GEN_H\n"
  append content "#define TH8_VERSION_GEN_H\n"
  append content "#define TH8_PRODUCT_VERSION  $patchLevel\n"
  append content "#define TH8_FILE_VERSION     $patchLevel\n"
  append content "\n"
  append content "#define TH8_PATCH_LEVEL      \"$patchLevel\"\n"
  append content "#define TH8_VERSION          \"$version\"\n"
  append content "\n"
  append content "#define TH8_RC_PATCH_LEVEL   $rcPatchLevelToken\n"
  append content "#define TH8_RC_VERSION       $rcVersionTuple\n"
  append content "\n"
  append content "#define TH8_SOURCE_ID        \"$srcId\"\n"
  append content "#define TH8_SOURCE_TIMESTAMP \"$srcDatetime\"\n"
  append content "#define TH8_SOURCE_TAGS      \"$srcTags\"\n"
  append content "#define TH8_SOURCE_VCS       \"$srcVcs\"\n"
  append content "#endif\n"

  #
  # Only write if content has changed (avoids recompilation).
  #

  set changed 1
  if {[file exists $outFile]} then {
    set fd [open $outFile r]
    set old [read $fd]
    close $fd
    if {$old eq $content} then {
      set changed 0
    }
  }

  if {$changed} then {
    #
    # Ensure the output directory exists.
    #

    set dir [file dirname $outFile]
    if {$dir ne "" && $dir ne "."} then {
      file mkdir $dir
    }

    set fd [open $outFile w]
    puts -nonewline $fd $content
    close $fd
    puts "  Generated $outFile"
  }
}

eval main $argv
