#!/usr/bin/env tclsh
###############################################################################
#
# regex_amalg.tcl --
#
#     Pre-amalgamate the Spencer regex engine into a single C file
#     suitable for inclusion in the TH8 amalgamation.
#
#     The Spencer engine uses `struct vars` with different definitions
#     in regcomp.c and regexec.c.  In a single translation unit, the
#     two definitions collide.  This script resolves the conflict by
#     wrapping each file in #define vars comp_vars / exec_vars blocks,
#     which the preprocessor propagates into all #included headers.
#
#     Requires: tools/regex_vendor.tcl has been run first.
#
# Usage:
#     tclsh tools/regex_amalg.tcl bin/
#
# Output:
#     bin/regex_amalg.c
#
# Copyright (c) 2026 by Joe Mistachkin.  All rights reserved.
#
# See the file "license.terms" for information on usage and redistribution of
# this file, and for a DISCLAIMER OF ALL WARRANTIES.
#
###############################################################################

set buildDir "externals/regex/build"
set output [file join [lindex $argv 0] regex_amalg.c]

proc readFile {path} {
  set fd [open $path r]
  set data [read $fd]
  close $fd
  return $data
}

if {![file exists [file join $buildDir "regcomp.c"]]} then {
  puts stderr "Run 'make regex_vendor' first."
  exit 1
}

file mkdir [file dirname $output]

set out ""
append out "/*\n"
append out "** regex_amalg.c -- Spencer regex engine, pre-amalgamated for TH8.\n"
append out "**\n"
append out "** Generated by tools/regex_amalg.tcl.  DO NOT EDIT.\n"
append out "**\n"
append out "** The struct vars conflict between regcomp.c and regexec.c is\n"
append out "** resolved via #define vars comp_vars / exec_vars so the\n"
append out "** preprocessor renames all references including those in\n"
append out "** #included headers (regguts.h etc.).\n"
append out "*/\n\n"
append out "#if defined(TH8_ENABLE_REGEXP)\n\n"

#
# inlineRegexFile --
#
#     Read a regex engine source file and inline it, recursively
#     resolving #include "regc_*.c" directives.  This produces a
#     fully self-contained amalgamation with no external file
#     dependencies.
#
set ::regexInlining {}

proc inlineRegexFile {path buildDir} {
  set tail [file tail $path]

  # Recursion guard.
  if {$tail in $::regexInlining} then {
    return "/* recursion guard: $tail */\n"
  }
  lappend ::regexInlining $tail

  set data [readFile $path]
  set result ""
  append result "#line 1 \"$path\"\n"
  set lineNum 0
  foreach line [split $data \n] {
    incr lineNum
    if {[regexp {^#\s*include\s+"([^"]+)"} $line -> incFile]} then {
            set incPath [file join $buildDir $incFile]
            if {[file exists $incPath]} then {
                append result "/*** Begin inlined: $incFile ***/\n"
                append result [inlineRegexFile $incPath $buildDir]
                append result "/*** End inlined: $incFile ***/\n"
                append result "#line [expr {$lineNum + 1}] \"$path\"\n"
                continue
            }
        }
        append result $line "\n"
    }

    # Remove from recursion stack.
    set idx [lsearch -exact $::regexInlining $tail]
    if {$idx >= 0} then {
        set ::regexInlining [lreplace $::regexInlining $idx $idx]
    }

    return $result
}

#
# regcomp.c: #define vars comp_vars
#
append out "/* ===== BEGIN regcomp.c (struct vars -> comp_vars) ===== */\n"
append out "#define vars comp_vars\n"
append out [inlineRegexFile [file join $buildDir regcomp.c] $buildDir]
append out "#undef vars\n"
append out "/* ===== END regcomp.c ===== */\n\n"

#
# regexec.c: #define vars exec_vars
#
append out "/* ===== BEGIN regexec.c (struct vars -> exec_vars) ===== */\n"
append out "#define vars exec_vars\n"
append out [inlineRegexFile [file join $buildDir regexec.c] $buildDir]
append out "#undef vars\n"
append out "/* ===== END regexec.c ===== */\n\n"

#
# regfree.c, regprefix.c, regerror.c: no struct vars conflict,
# no internal includes.
#
foreach f {regfree.c regprefix.c regerror.c} {
    append out "/* ===== BEGIN $f ===== */\n"
    append out [inlineRegexFile [file join $buildDir $f] $buildDir]
    append out "/* ===== END $f ===== */\n\n"
}

#
# Clean up all macros defined by regcustom_th8.h that would
# pollute subsequent code in the amalgamation.
#
append out "/*\n"
append out "** Undo regcustom_th8.h macro pollution so that subsequent\n"
append out "** code in the amalgamation sees the real C runtime.\n"
append out "*/\n"
foreach m {
    MALLOC FREE REALLOC INTERRUPT
    memcpy memcmp memset strlen strcmp strcpy strchr sprintf atoi qsort
    FLEXIBLE_ARRAY_MEMBER VS
} {
    append out "#undef $m\n"
}
append out "\n"


append out "#endif /* TH8_ENABLE_REGEXP */\n"

set fd [open $output w]
fconfigure $fd -translation binary
puts -nonewline $fd $out
close $fd

puts "Regex amalgamation: $output"
puts "  [llength [split $out \n]] lines (thin wrapper — actual code is #included)"
