#!/usr/bin/env tclsh
###############################################################################
#
# tommath_amalg.tcl --
#
#     Generate a single-file amalgamation of libtommath for TH8.
#
#     Produces bin/tommath_amalg.c that #includes all bn_*.c files
#     from externals/tommath/ with LTM_ALL defined.  This makes
#     libtommath compilable as a single translation unit, suitable
#     for inclusion in the TH8 amalgamation.
#
# Usage:
#     tclsh tools/tommath_amalg.tcl bin/
#
# Output:
#     bin(-static)?/tommath_amalg.c
#
# Copyright (c) 2026 by Joe Mistachkin.  All rights reserved.
#
# See the file "license.terms" for information on usage and redistribution of
# this file, and for a DISCLAIMER OF ALL WARRANTIES.
#
###############################################################################

set vendorDir "externals/tommath/vendor"
set buildDir  "externals/tommath/build"
set output [file join [lindex $argv 0] tommath_amalg.c]

if {![file exists [file join $vendorDir "tommath.h"]]} then {
  puts stderr "libtommath not found in $vendorDir"
  puts stderr "Download from https://github.com/libtom/libtommath"
  exit 1
}

file mkdir [file dirname $output]
#
# Step 1: Clean and recreate build/.  Copy all vendor files,
# then apply any patches from patches/ (overwriting vendor).
#
if {[file exists $buildDir]} then {
  file delete -force $buildDir
}
file mkdir $buildDir

set vendorFiles [concat \
    [glob -nocomplain [file join $vendorDir "*.h"]] \
    [glob -nocomplain [file join $vendorDir "*.c"]]]

foreach f $vendorFiles {
  file copy -force $f [file join $buildDir [file tail $f]]
}

# Apply patches: any .c or .h file in patches/ overwrites
# the corresponding file in build/.
set patchDir [file join [file dirname $vendorDir] patches]
foreach f [glob -nocomplain [file join $patchDir "*.c"] \
    [file join $patchDir "*.h"]] {
  set tail [file tail $f]
  set dst [file join $buildDir $tail]
  # Only copy if it's a regular file (not a diff).
  if {[string match "*.c" $tail] || [string match "*.h" $tail]} then {
    set fd [open $f r]
    set first [gets $fd]
    close $fd
    # Skip diff/patch files (start with --- or diff).
    if {![string match "---*" $first] && ![string match "diff*" $first]} then {
      file copy -force $f $dst
    }
  }
}

#
# Step 2: Collect all source files from build/.
#
set bnFiles [lsort [concat \
    [glob -nocomplain [file join $buildDir "mp_*.c"]] \
    [glob -nocomplain [file join $buildDir "s_mp_*.c"]]]]
if {[llength $bnFiles] == 0} then {
  set bnFiles [lsort [glob -nocomplain [file join $buildDir "bn_*.c"]]]
}
if {[llength $bnFiles] == 0} then {
  puts stderr "No mp_*.c, s_mp_*.c, or bn_*.c files found in $buildDir"
  exit 1
}

set out ""
append out "/*\n"
append out "** tommath_amalg.c -- libtommath amalgamation for TH8.\n"
append out "**\n"
append out "** Generated by tools/tommath_amalg.tcl.  DO NOT EDIT.\n"
append out "**\n"
append out "** Compiles the entire libtommath library as a single\n"
append out "** translation unit by #including all bn_*.c files.\n"
append out "*/\n\n"

append out "#if defined(TH8_ENABLE_BIGINT)\n\n"

#
# LTM_ALL enables all function classes.  It must be defined
# before the first #include of tommath_class.h, which checks
# it immediately.  tommath_superclass.h also defines LTM_ALL
# (without a value), so we match that form exactly to avoid
# -Wmacro-redefined warnings.
#
# MP_NO_FILE disables the mp_fread/mp_fwrite FILE* functions
# (we don't need them and they pull in <stdio.h> for FILE).
#
# MP_MALLOC/MP_REALLOC/MP_CALLOC/MP_FREE route all libtommath
# allocations through the TH8 platform allocator.  When the
# interpreter is cancelled or exceeds resource limits, the
# bridge returns NULL, causing libtommath to abort gracefully
# via its MP_MEM error path.
#
append out "#define MP_NO_FILE 1\n"
append out "#define LTM_ALL\n\n"
append out "/* Route libtommath memory through TH8 platform allocator. */\n"
append out "#include \"th8.h\"\n"
append out "#include \"th8_int.h\"  /* For bridge declarations. */\n\n"
append out "#define MP_MALLOC  th8_bigint_malloc\n"
append out "#define MP_CALLOC  th8_bigint_calloc\n"
append out "#define MP_REALLOC th8_bigint_realloc\n"
append out "#define MP_FREE    th8_bigint_free\n\n"

#
# Emit all libtommath headers ONCE at the top.
#
# Since LTM_ALL is defined, the class system (tommath_class.h /
# tommath_superclass.h) unconditionally enables all functions.
# Re-including them per .c file is redundant and wastes ~96K lines.
# We emit them once here, then strip #include directives from .c files.
#
set headerOrder {
  tommath_superclass.h
  tommath_class.h
  tommath.h
  tommath_cutoffs.h
  tommath_private.h
}

foreach hdr $headerOrder {
  set hdrPath [file join $buildDir $hdr]
  if {[file exists $hdrPath]} then {
    set fd [open $hdrPath r]
    set hdrData [read $fd]
    close $fd
    append out "/*** Begin header: $hdr ***/\n"
    append out "#line 1 \"$hdrPath\"\n"
    foreach line [split $hdrData \n] {
      if {[regexp {^#\s*include\s+"([^"]+)"} $line]} then {
		append out "/* stripped: $line */\n"
	    } else {
		append out $line "\n"
		#
		# Patch: insert missing C99 standard headers after
		# <limits.h> in tommath_private.h.  MSVC in C mode
		# does not provide bool, size_t, or uint64_t without
		# explicit includes.
		#
		if {$hdr eq "tommath_private.h"
			&& [regexp {^#\s*include\s+<limits\.h>} $line]} then {
		    append out "#include <stddef.h>\n"
		    append out "#include <stdbool.h>\n"
		    append out "#include <stdint.h>\n"
		}
	    }
	}
	append out "/*** End header: $hdr ***/\n\n"
    }
}

#
# inlineTommathFile --
#
#     Read a libtommath .c file and inline it, STRIPPING all
#     #include "..." directives.  Since LTM_ALL is defined and
#     all headers are emitted once at the top of the amalgamation,
#     the per-file includes are redundant (the class system is a
#     no-op when LTM_ALL is set).
#

proc inlineTommathFile {path buildDir} {
    set fd [open $path r]
    set data [read $fd]
    close $fd
    set result ""
    append result "#line 1 \"$path\"\n"
    set lineNum 0
    foreach line [split $data \n] {
        incr lineNum
        if {[regexp {^#\s*include\s+"([^"]+)"} $line]} then {
          append result "/* stripped: $line */\n"
          continue
        }
        append result $line "\n"
      }
      return $result
    }

    foreach f $bnFiles {
      set tail [file tail $f]

      append out "/*** Begin inlined: $tail ***/\n"
      append out [inlineTommathFile $f $buildDir]
      append out "/*** End inlined: $tail ***/\n\n"
    }

    append out "\n#endif /* TH8_ENABLE_BIGINT */\n"

    set fd [open $output w]
    fconfigure $fd -translation binary
    puts -nonewline $fd $out
    close $fd

    puts "Tommath amalgamation: $output"
    puts "  Files: [llength $bnFiles]"
    puts "  Lines: [llength [split $out \n]]"
