/*
 * th8Decls.h --
 *
 *	TH8 stubs table declarations.  Auto-generated by
 *	tools/mkstubs.tcl.  DO NOT EDIT BY HAND.
 *
 * Copyright (c) 2026 by Joe Mistachkin.  All rights reserved.
 *
 * See the file "license.terms" for information on usage and redistribution of
 * this file, and for a DISCLAIMER OF ALL WARRANTIES.
 */

#ifndef TH8_DECLS_H
#define TH8_DECLS_H

/*
 * The stubs table aggregates the public API from every public
 * header, so th8Decls.h must pull in each of them for the
 * types they define (e.g. Th8_GetCommandsProc from th8_plugin.h,
 * Th8_Hash / Th8_HashEntry from th8_hash.h).  Keep this list in
 * sync with the sibling-header list in mkstubs.tcl.
 */
#include "th8.h"
#include "th8_hash.h"
#include "th8_plugin.h"

/*
 * The stubs table: a struct of function pointers for every
 * public TH8 API function.
 */

typedef struct Th8StubsTable {
    int magic;     /* Must be TH8_STUBS_MAGIC. */
    int version;   /* Stubs table version. */
    int (*th8_MergePlatform)(Th8_Platform *pDst, const Th8_Platform *pSrc);
    Th8_Platform *(*th8_ClonePlatform)(const Th8_Platform *pSrc);
    void (*th8_FreePlatform)(Th8_Platform *pPlatform);
    int (*th8_MergePlatformInterp)(
        Th8_Interp *interp,
        const Th8_Platform *pSrc);
    int (*th8_Initialize)(Th8_Platform *pPlatform);
    int (*th8_Finalize)(Th8_Platform *pPlatform);
    const void *(*th8_GetInternalStubs)(void);
    int (*th8_IntCmpXchg)(
        Th8_Interp *interp,
        volatile int *pTarget,
        int iExchange,
        int iComparand);
    Th8_Interp *(*th8_CreateInterp)(Th8_Platform *pPlatform);
    int (*th8_RestoreInterp)(Th8_Interp *interp, int flags);
    void (*th8_DeleteInterp)(Th8_Interp *interp);
    int (*th8_Ready)(Th8_Interp *interp);
    int (*th8_CancelEval)(
        Th8_Interp *interp,
        const char *zMsg,
        size_t nMsg,
        int flags);
    void (*th8_ThreadInit)(void);
    void (*th8_ThreadDone)(void);
    void *(*th8_CreateAsyncState)(Th8_Interp *interp, void *pCtx);
    int (*th8_FinalizeAsyncState)(void *pState);
    int (*th8_QueueEvent)(
        void *pState,
        int (*xCallback)(Th8_Interp *interp, void *pCtx));
    int (*th8_DrainQueueEvents)(Th8_Interp *interp);
    int (*th8_IsCanceled)(Th8_Interp *interp, int flags);
    int (*th8_IsBeingUnwound)(Th8_Interp *interp);
    void (*th8_ResetCancel)(Th8_Interp *interp);
    void (*th8_Exit)(Th8_Interp *interp);
    int (*th8_IsExited)(Th8_Interp *interp);
    void (*th8_ResetExit)(Th8_Interp *interp);
    int (*th8_Freeze)(Th8_Interp *interp);
    int (*th8_Thaw)(Th8_Interp *interp);
    int (*th8_IsSuspended)(Th8_Interp *interp);
    int (*th8_SetDebugCallback)(
        Th8_Interp *interp,
        Th8_DebugProc xDebug,
        void *pCtx);
    int (*th8_SetBreakpoint)(
        Th8_Interp *interp,
        const char *zScript,
        size_t nScript,
        int nLine,
        int *pBreakpointId);
    int (*th8_ClearBreakpoint)(Th8_Interp *interp, int breakpointId);
    int (*th8_ClearAllBreakpoints)(Th8_Interp *interp);
    int (*th8_SetStepMode)(Th8_Interp *interp, int mode);
    int (*th8_GetStepMode)(Th8_Interp *interp);
    int (*th8_GetFrameCount)(Th8_Interp *interp);
    int (*th8_GetFrameInfo)(
        Th8_Interp *interp,
        int frameIndex,
        const char **pzProc,
        size_t *pnProc,
        const char **pzScript,
        size_t *pnScript,
        int *pnLine);
    int (*th8_EvalAtFrame)(
        Th8_Interp *interp,
        int frameIndex,
        const char *zScript,
        size_t nScript);
    int (*th8_CoroCreate)(
        Th8_Interp *interp,
        const char *zName,
        size_t nName,
        const char *zBody,
        size_t nBody);
    int (*th8_CoroYield)(
        Th8_Interp *interp,
        const char *zValue,
        size_t nValue);
    int (*th8_Eval)(
        Th8_Interp *interp,
        int iFrame,
        const char *zProg,
        size_t nProg,
        const char *zName,
        size_t nName);
    int (*th8_EvalTrusted)(
        Th8_Interp *interp,
        int iFrame,
        const char *zProg,
        size_t nProg,
        const char *zName,
        size_t nName);
    int (*th8_EvalDownlevel)(
        Th8_Interp *interp,
        const char *zProg,
        size_t nProg,
        const char *zName,
        size_t nName);
#if defined(TH8_ENABLE_EXPRESSIONS)
    int (*th8_Expr)(
        Th8_Interp *interp,
        const char *zExpr,
        size_t nExpr,
        const char *zName,
        size_t nName);
#else
    void *th8_Expr;
#endif
    int (*th8_Complete)(const char *zScript, size_t nScript);
    int (*th8_EvalFile)(Th8_Interp *interp, const char *zName, size_t nName);
    int (*th8_EvalFileAsData)(
        Th8_Interp *interp,
        const char *zName,
        size_t nName,
        const unsigned char **pzData,
        size_t *pnData,
        void *pCtx);
    int (*th8_NREval)(
        Th8_Interp *interp,
        const char *zProg,
        size_t nProg,
        const char *zName,
        size_t nName);
    int (*th8_NRAddCallback)(
        Th8_Interp *interp,
        Th8_CallbackProc xProc,
        void *p0,
        void *p1,
        void *p2,
        void *p3);
    int (*th8_NREvalInFrame)(
        Th8_Interp *interp,
        int iFrame,
        const char *zProg,
        size_t nProg,
        const char *zName,
        size_t nName);
#if defined(TH8_ENABLE_VARIABLES)
    int (*th8_ExistsVar)(Th8_Interp *interp, const char *zVar, size_t nVar);
#else
    void *th8_ExistsVar;
#endif
#if defined(TH8_ENABLE_VARIABLES)
    int (*th8_ExistsArrayVar)(
        Th8_Interp *interp,
        const char *zVar,
        size_t nVar);
#else
    void *th8_ExistsArrayVar;
#endif
#if defined(TH8_ENABLE_VARIABLES)
    int (*th8_GetVar)(Th8_Interp *interp, const char *zVar, size_t nVar);
#else
    void *th8_GetVar;
#endif
#if defined(TH8_ENABLE_VARIABLES)
    int (*th8_SetVar)(
        Th8_Interp *interp,
        const char *zVar,
        size_t nVar,
        const char *zVal,
        size_t nVal);
#else
    void *th8_SetVar;
#endif
#if defined(TH8_ENABLE_VARIABLES)
    int (*th8_LinkVar)(
        Th8_Interp *interp,
        const char *zLocal,
        size_t nLocal,
        int iFrame,
        const char *zRemote,
        size_t nRemote);
#else
    void *th8_LinkVar;
#endif
#if defined(TH8_ENABLE_VARIABLES)
    int (*th8_UnsetVar)(Th8_Interp *interp, const char *zVar, size_t nVar);
#else
    void *th8_UnsetVar;
#endif
    int (*th8_CreateCommand)(
        Th8_Interp *interp,
        const char *zName,
        Th8_CommandProc xProc,
        void *pContext,
        void (*xDel)(Th8_Interp *, void *),
        th8_uint64_t *pToken);
    int (*th8_DeleteCommand)(Th8_Interp *interp, th8_uint64_t token);
    int (*th8_GetCommandInfo)(
        Th8_Interp *interp,
        const char *zName,
        size_t nName,
        Th8_CommandProc *pxProc,
        void **ppContext);
    void (*th8_SetCommandCopy)(
        Th8_Interp *interp,
        const char *zName,
        void *(*xCopy)(Th8_Interp *, void *));
    int (*th8_RenameCommand)(
        Th8_Interp *interp,
        const char *zOld,
        size_t nOld,
        const char *zNew,
        size_t nNew);
    int (*th8_RegisterExpansion)(
        Th8_Interp *interp,
        const char *zTag,
        size_t nTag,
        Th8_ExpansionProc xProc,
        void *pCtx);
    int (*th8_UnregisterExpansion)(
        Th8_Interp *interp,
        const char *zTag,
        size_t nTag);
    int (*th8_FindExpansion)(
        Th8_Interp *interp,
        const char *zTag,
        size_t nTag,
        Th8_ExpansionProc *pxProc,
        void **ppCtx);
    void (*th8_ListAppendExpansions)(
        Th8_Interp *interp,
        char **pzList,
        size_t *pnList,
        const char *zPat,
        size_t nPat);
    void (*th8_ListAppendBreakpoints)(
        Th8_Interp *interp,
        char **pzList,
        size_t *pnList);
#if defined(TH8_ENABLE_EXPRESSIONS)
    int (*th8_CreateMathFunc)(
        Th8_Interp *interp,
        const char *zName,
        size_t nName,
        int nArg,
        Th8_MathFuncProc xProc,
        void *pCtx);
#else
    void *th8_CreateMathFunc;
#endif
#if defined(TH8_ENABLE_EXPRESSIONS)
    int (*th8_DeleteMathFunc)(
        Th8_Interp *interp,
        const char *zName,
        size_t nName);
#else
    void *th8_DeleteMathFunc;
#endif
#if defined(TH8_ENABLE_EXPRESSIONS)
    int (*th8_FindMathFunc)(
        Th8_Interp *interp,
        const char *zName,
        size_t nName,
        int *pnArg,
        Th8_MathFuncProc *pxProc,
        void **ppCtx);
#else
    void *th8_FindMathFunc;
#endif
#if defined(TH8_ENABLE_EXPRESSIONS)
    void (*th8_ListAppendMathFunctions)(
        Th8_Interp *interp,
        char **pzList,
        size_t *pnList,
        const char *zPat,
        size_t nPat);
#else
    void *th8_ListAppendMathFunctions;
#endif
    int (*th8_GlobMatch)(
        Th8_Interp *interp,
        const char *zPat,
        size_t nPat,
        const char *zStr,
        size_t nStr);
    int (*th8_Subst)(Th8_Interp *interp, const char *z, size_t n, int flags);
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    int (*th8_RsaKeyLoad)(
        Th8_Interp *interp,
        const unsigned char *zData,
        size_t nData,
        Th8_RsaKey **ppKey);
#else
    void *th8_RsaKeyLoad;
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    void (*th8_RsaKeyFree)(Th8_Interp *interp, Th8_RsaKey *pKey);
#else
    void *th8_RsaKeyFree;
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    int (*th8_RsaKeyBitLen)(const Th8_RsaKey *pKey);
#else
    void *th8_RsaKeyBitLen;
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    int (*th8_RsaKeyHasPrivate)(const Th8_RsaKey *pKey);
#else
    void *th8_RsaKeyHasPrivate;
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    unsigned int (*th8_RsaKeyPubExp)(const Th8_RsaKey *pKey);
#else
    void *th8_RsaKeyPubExp;
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    const unsigned char
        *(*th8_RsaKeyModulus)(const Th8_RsaKey *pKey, size_t *pn);
#else
    void *th8_RsaKeyModulus;
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    const unsigned char
        *(*th8_RsaKeyPrivExp)(const Th8_RsaKey *pKey, size_t *pn);
#else
    void *th8_RsaKeyPrivExp;
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    const unsigned char
        *(*th8_RsaKeyPrime1)(const Th8_RsaKey *pKey, size_t *pn);
#else
    void *th8_RsaKeyPrime1;
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    const unsigned char
        *(*th8_RsaKeyPrime2)(const Th8_RsaKey *pKey, size_t *pn);
#else
    void *th8_RsaKeyPrime2;
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    int (*th8_RsaKeyToken)(
        Th8_Interp *interp,
        const Th8_RsaKey *pKey,
        unsigned char zOut[8]);
#else
    void *th8_RsaKeyToken;
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    int (*th8_RsaKeyTokenHex)(
        Th8_Interp *interp,
        const Th8_RsaKey *pKey,
        char zOut[17]);
#else
    void *th8_RsaKeyTokenHex;
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    int (*th8_HarpySigLoad)(
        Th8_Interp *interp,
        const char *zData,
        size_t nData,
        unsigned char **ppSig,
        size_t *pnSig,
        char **ppToken);
#else
    void *th8_HarpySigLoad;
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    int (*th8_RsaVerify)(
        Th8_Interp *interp,
        const Th8_RsaKey *pKey,
        const unsigned char *zData,
        size_t nData,
        const unsigned char *zSig,
        size_t nSig);
#else
    void *th8_RsaVerify;
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    int (*th8_RsaSign)(
        Th8_Interp *interp,
        const Th8_RsaKey *pKey,
        const unsigned char *zData,
        size_t nData,
        unsigned char **ppSig,
        size_t *pnSig);
#else
    void *th8_RsaSign;
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    int (*th8_Sha512Hex)(
        Th8_Interp *interp,
        const unsigned char *zData,
        size_t nData,
        char zOut[129]);
#else
    void *th8_Sha512Hex;
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    int (*th8_RsaExtractHash)(
        Th8_Interp *interp,
        const Th8_RsaKey *pKey,
        const unsigned char *zSig,
        size_t nSig,
        char zOut[129]);
#else
    void *th8_RsaExtractHash;
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    int (*th8_InstallSignedPolicy)(Th8_Interp *interp, void **ppCtx);
#else
    void *th8_InstallSignedPolicy;
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    void (*th8_RemoveSignedPolicy)(Th8_Interp *interp, void *pCtx);
#else
    void *th8_RemoveSignedPolicy;
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    int (*th8_PolicyPreloadKey)(
        Th8_Interp *interp,
        void *pCtx,
        Th8_RsaKey *pKey);
#else
    void *th8_PolicyPreloadKey;
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    int (*th8_PolicyGetKeyTokens)(Th8_Interp *interp, void *pCtx);
#else
    void *th8_PolicyGetKeyTokens;
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    const Th8_RsaKey *(*th8_PolicyFindKey)(
        Th8_Interp *interp,
        void *pCtx,
        const char *zToken,
        size_t nToken);
#else
    void *th8_PolicyFindKey;
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    int (*th8_EnableSignedPolicy)(
        Th8_Interp *interp,
        void **ppCtx,
        int bEnable);
#else
    void *th8_EnableSignedPolicy;
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    int (*th8_EvalFileAndRsaKeyLoad)(
        Th8_Interp *interp,
        const char *zName,
        size_t nName,
        void *pCtx,
        int bPreload);
#else
    void *th8_EvalFileAndRsaKeyLoad;
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    const unsigned char *(*th8_GetEmbeddedKeyRoot)(size_t *pnData);
#else
    void *th8_GetEmbeddedKeyRoot;
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    const unsigned char *(*th8_GetEmbeddedKey0)(size_t *pnData);
#else
    void *th8_GetEmbeddedKey0;
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    Th8_RsaKey *(*th8_GetPublicKeyZero)(Th8_Interp *interp);
#else
    void *th8_GetPublicKeyZero;
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    int (*th8_GetPublicKeyZeroToken)(Th8_Interp *interp, char zOut[17]);
#else
    void *th8_GetPublicKeyZeroToken;
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    Th8_RsaKey *(*th8_GetPublicKeyRoot)(Th8_Interp *interp);
#else
    void *th8_GetPublicKeyRoot;
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    int (*th8_GetPublicKeyRootToken)(Th8_Interp *interp, char zOut[17]);
#else
    void *th8_GetPublicKeyRootToken;
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    const unsigned char *(*th8_GetEmbeddedKeyTime)(size_t *pnData);
#else
    void *th8_GetEmbeddedKeyTime;
#endif
    const Th8_KeyringEntry *(*th8_GetEmbeddedKeyring)(size_t *pnEntries);
#if defined(TH8_ENABLE_CRYPTOGRAPHY) && defined(TH8_ENABLE_TEST_KEY)
    const unsigned char *(*th8_GetEmbeddedKeyTest)(size_t *pnData);
#else
    void *th8_GetEmbeddedKeyTest;
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY) && defined(TH8_ENABLE_TEST_KEY)
    Th8_RsaKey *(*th8_GetPublicKeyTest)(Th8_Interp *interp);
#else
    void *th8_GetPublicKeyTest;
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY) && defined(TH8_ENABLE_TEST_KEY)
    int (*th8_GetPublicKeyTestToken)(Th8_Interp *interp, char zOut[17]);
#else
    void *th8_GetPublicKeyTestToken;
#endif
    int (*th8_Pledge)(
        Th8_Interp *interp,
        const char *zPromises,
        const char *zExecPromises);
    int (*th8_Unveil)(
        Th8_Interp *interp,
        const char *zPath,
        const char *zPermissions);
    int (*th8_SetResult)(Th8_Interp *interp, const char *z, size_t n);
    void (*th8_SetResultStatic)(Th8_Interp *interp, const char *z, size_t n);
    void (*th8_ClearResult)(Th8_Interp *interp);
    const char *(*th8_GetResult)(Th8_Interp *interp, size_t *pN);
    char *(*th8_TakeResult)(Th8_Interp *interp, size_t *pN);
    int (*th8_IsResultSensitive)(Th8_Interp *interp);
#if defined(TH8_ENABLE_VARIABLES) && defined(TH8_ENABLE_CRYPTOGRAPHY)
    void (*th8_MarkResultSensitive)(Th8_Interp *interp);
#else
    void *th8_MarkResultSensitive;
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    int (
        *th8_SetResultSensitive)(Th8_Interp *interp, const char *z, size_t n);
#else
    void *th8_SetResultSensitive;
#endif
    int (*th8_ErrorMessage)(
        Th8_Interp *interp,
        const char *zPre,
        const char *z,
        size_t n);
    int (*th8_SetResultInt)(Th8_Interp *interp, int iVal);
    int (*th8_SetResultWideInt)(Th8_Interp *interp, th8_int64_t wVal);
    int (*th8_SetResultDouble)(Th8_Interp *interp, double rVal);
    int (*th8_GetErrorLine)(Th8_Interp *interp);
    int (*th8_GetEvalDepth)(Th8_Interp *interp);
    void (*th8_SetErrorLine)(Th8_Interp *interp, int nLine);
    int (*th8_GetLine)(Th8_Interp *interp);
    void (*th8_SetStepLimit)(Th8_Interp *interp, th8_int64_t nLimit);
    th8_int64_t (*th8_GetStepLimit)(Th8_Interp *interp);
    th8_int64_t (*th8_GetStepCount)(Th8_Interp *interp);
    void (*th8_ResetStepCount)(Th8_Interp *interp);
    void (*th8_SetStepCount)(Th8_Interp *interp, th8_int64_t nCount);
    void (*th8_SetResultLimit)(Th8_Interp *interp, size_t nLimit);
    size_t (*th8_GetResultLimit)(Th8_Interp *interp);
#if defined(TH8_ENABLE_BIGINT)
    int (*th8_EnableBigint)(Th8_Interp *interp, int bEnable);
#else
    void *th8_EnableBigint;
#endif
#if defined(TH8_ENABLE_BIGINT)
    int (*th8_IsBigintEnabled)(Th8_Interp *interp);
#else
    void *th8_IsBigintEnabled;
#endif
    int (*th8_GetExprFeatures)(Th8_Interp *interp);
    int (*th8_SetExprFeatures)(Th8_Interp *interp, int flags);
    void (*th8_SetOverflowCheck)(Th8_Interp *interp, int bEnable);
    int (*th8_GetOverflowCheck)(Th8_Interp *interp);
    void (*th8_SetAllocLimit)(Th8_Interp *interp, size_t nLimit);
    size_t (*th8_GetAllocLimit)(Th8_Interp *interp);
    size_t (*th8_GetAllocBytes)(Th8_Interp *interp);
#if defined(TH8_ENABLE_LOAD)
    int (*th8_EnableLoad)(Th8_Interp *interp, int bEnable);
#else
    void *th8_EnableLoad;
#endif
#if defined(TH8_ENABLE_LOAD)
    int (*th8_IsLoadEnabled)(Th8_Interp *interp);
#else
    void *th8_IsLoadEnabled;
#endif
    int (*th8_EnableSignedOnly)(Th8_Interp *interp, int bEnable);
    int (*th8_IsSignedOnlyEnabled)(Th8_Interp *interp);
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    void (*th8_SaveSignedOnly)(Th8_Interp *interp, void *pSaved);
#else
    void *th8_SaveSignedOnly;
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    void (*th8_RestoreSignedOnly)(Th8_Interp *interp, const void *pSaved);
#else
    void *th8_RestoreSignedOnly;
#endif
#if defined(TH8_ENABLE_VARIABLES)
    int (*th8_DeclareSystemVar)(
        Th8_Interp *interp,
        const char *zName,
        size_t nName);
#else
    void *th8_DeclareSystemVar;
#endif
#if defined(TH8_ENABLE_VARIABLES)
    int (*th8_IsSystemVar)(
        Th8_Interp *interp,
        const char *zName,
        size_t nName);
#else
    void *th8_IsSystemVar;
#endif
#if defined(TH8_ENABLE_LOAD)
    int (*th8_Load)(
        Th8_Interp *interp,
        const char *zName,
        size_t nName,
        const char *zProc,
        size_t nProc);
#else
    void *th8_Load;
#endif
#if defined(TH8_ENABLE_LOAD)
    int (*th8_EnableUnload)(Th8_Interp *interp, int flags);
#else
    void *th8_EnableUnload;
#endif
#if defined(TH8_ENABLE_LOAD)
    int (*th8_Unload)(
        Th8_Interp *interp,
        const char *zName,
        size_t nName,
        const char *zProc,
        size_t nProc,
        int bClose);
#else
    void *th8_Unload;
#endif
    void (*th8_SetPolicyCallback)(
        Th8_Interp *interp,
        Th8_PolicyProc xProc,
        void *pCtx);
#if defined(TH8_ENABLE_LOAD)
    void (*th8_SetPreLoadCallback)(
        Th8_Interp *interp,
        Th8_PreLoadProc xProc,
        void *pCtx);
#else
    void *th8_SetPreLoadCallback;
#endif
    void (*th8_GetPolicyCallback)(
        Th8_Interp *interp,
        Th8_PolicyProc *pxProc,
        void **ppCtx);
    int (*th8_GetFrameObjv)(
        Th8_Interp *interp,
        int iLevel,
        int *pArgc,
        const char ***pArgv,
        size_t **pArgl);
    int (*th8_StringAppend)(
        Th8_Interp *interp,
        char **pzStr,
        size_t *pnStr,
        const char *zApp,
        size_t nApp);
    int (*th8_ListAppend)(
        Th8_Interp *interp,
        char **pzList,
        size_t *pnList,
        const char *zElem,
        size_t nElem);
    int (*th8_SplitList)(
        Th8_Interp *interp,
        const char *zList,
        size_t nList,
        char ***pazElem,
        size_t **panElem,
        int *pnCount,
        int flags);
    int (*th8_ToInt)(Th8_Interp *interp, const char *z, size_t n, int *piVal);
    int (*th8_ToBoolean)(
        Th8_Interp *interp,
        const char *z,
        size_t n,
        int *pbVal);
    int (*th8_ToWideInt)(
        Th8_Interp *interp,
        const char *z,
        size_t n,
        th8_int64_t *pwVal);
    int (*th8_ToDouble)(
        Th8_Interp *interp,
        const char *z,
        size_t n,
        double *prVal);
    int (*th8_ListAppendCommands)(Th8_Interp *interp, char **pz, size_t *pn);
    int (*th8_ListAppendCommandsMatching)(
        Th8_Interp *interp,
        char **pz,
        size_t *pn,
        Th8_CommandProc xMatch1,
        Th8_CommandProc xMatch2);
#if defined(TH8_ENABLE_VARIABLES)
    int (*th8_ListAppendVariables)(Th8_Interp *interp, char **pz, size_t *pn);
#else
    void *th8_ListAppendVariables;
#endif
#if defined(TH8_ENABLE_VARIABLES)
    int (*th8_ListAppendNsVariables)(
        Th8_Interp *interp,
        const char *zNs,
        size_t nNs,
        char **pz,
        size_t *pn);
#else
    void *th8_ListAppendNsVariables;
#endif
#if defined(TH8_ENABLE_VARIABLES)
    int (*th8_ListAppendGlobalVariables)(
        Th8_Interp *interp,
        char **pz,
        size_t *pn);
#else
    void *th8_ListAppendGlobalVariables;
#endif
#if defined(TH8_ENABLE_VARIABLES)
    int (*th8_ListAppendVarLinks)(Th8_Interp *interp, char **pz, size_t *pn);
#else
    void *th8_ListAppendVarLinks;
#endif
#if defined(TH8_ENABLE_VARIABLES)
    int (*th8_ListAppendArray)(
        Th8_Interp *interp,
        const char *zArr,
        size_t nArr,
        char **pz,
        size_t *pn);
#else
    void *th8_ListAppendArray;
#endif
    int (*th8_WrongNumArgs)(Th8_Interp *interp, const char *zMsg);
    int (*th8_CallSubCommand)(
        Th8_Interp *interp,
        void *ctx,
        int argc,
        const char **argv,
        size_t *argl,
        const Th8_SubCommand *aSub);
    int (*th8_ReportTaint)(
        Th8_Interp *interp,
        const char *zTitle,
        const char *zStr,
        size_t nStr);
    int (*th8_Input)(
        Th8_Interp *interp,
        char **pzOut,
        size_t *pnOut,
        int flags);
    int (*th8_Output)(Th8_Interp *interp, const char *z, size_t n, int flags);
    int (*th8_OutputError)(Th8_Interp *interp, const char *z, size_t n);
#if defined(TH8_PLUGIN_IO)
    int (*th8_GetInput)(Th8_Interp *interp, void **pChannel);
#else
    void *th8_GetInput;
#endif
#if defined(TH8_PLUGIN_IO)
    int (*th8_RedirectInput)(Th8_Interp *interp, void *channel);
#else
    void *th8_RedirectInput;
#endif
#if defined(TH8_PLUGIN_IO)
    int (*th8_GetOutput)(Th8_Interp *interp, void **pChannel);
#else
    void *th8_GetOutput;
#endif
#if defined(TH8_PLUGIN_IO)
    int (*th8_RedirectOutput)(Th8_Interp *interp, void *channel);
#else
    void *th8_RedirectOutput;
#endif
#if defined(TH8_PLUGIN_IO)
    int (*th8_GetErrorOutput)(Th8_Interp *interp, void **pChannel);
#else
    void *th8_GetErrorOutput;
#endif
#if defined(TH8_PLUGIN_IO)
    int (*th8_RedirectErrorOutput)(Th8_Interp *interp, void *channel);
#else
    void *th8_RedirectErrorOutput;
#endif
    int (*th8_GetData)(
        Th8_Interp *interp,
        const char *zName,
        size_t nName,
        char **pzOut,
        size_t *pnOut,
        int flags);
    int (*th8_DataExists)(
        Th8_Interp *interp,
        const char *zName,
        size_t nName,
        int *pAttrs);
    char *(*th8_NormalizePath)(
        Th8_Interp *interp,
        const char *zPath,
        size_t nPath);
    char *(*th8_GetCwd)(Th8_Interp *interp);
    int (*th8_SetCwd)(Th8_Interp *interp, const char *zPath, size_t nPath);
    int (*th8_GetRealPath)(
        Th8_Interp *interp,
        const char *zPath,
        size_t nPath,
        char *zBuf,
        size_t nBuf);
    int (*th8_GetRootPath)(
        Th8_Interp *interp,
        const char *zPath,
        size_t nPath,
        char *zBuf,
        size_t nBuf);
    int (*th8_SameFile)(
        Th8_Interp *interp,
        const char *zName1,
        size_t nName1,
        const char *zName2,
        size_t nName2);
    int (*th8_SetBasePath)(const char *zPath, size_t nPath);
    const char *(*th8_GetBasePath)(void);
    Th8_Hash *(*th8_HashNew)(Th8_Interp *interp);
    void (*th8_HashDelete)(Th8_Interp *interp, Th8_Hash *pHash);
    void (*th8_HashIterate)(
        Th8_Interp *interp,
        Th8_Hash *pHash,
        int (*xCallback)(Th8_HashEntry *, void *),
        void *pCtx);
    void (*th8_HashIterateOrdered)(
        Th8_Interp *interp,
        Th8_Hash *pHash,
        int (*xCallback)(Th8_HashEntry *, void *),
        void *pCtx);
    Th8_HashEntry *(*th8_HashFind)(
        Th8_Interp *interp,
        Th8_Hash *pHash,
        const char *zKey,
        size_t nKey,
        int op);
    void (*th8_HashRemove)(
        Th8_Interp *interp,
        Th8_Hash *pHash,
        const char *zKey,
        size_t nKey);
    void (*th8SeedHash)(Th8_Platform *pPlatform);
    struct Th8_Hash *(*th8_GetPackageHash)(Th8_Interp *interp);
    Th8_Hash *(*th8_GetMathFuncHash)(Th8_Interp *interp);
    int (*th8_IterateArraySearches)(
        Th8_Interp *interp,
        int (*xCallback)(
            const char *zArray,
            size_t nArray,
            const char *zSid,
            size_t nSid,
            void *pCtx),
        void *pCtx);
    const char *(*th8_GetPackageUnknown)(Th8_Interp *interp);
    void (*th8_SetPackageUnknown)(
        Th8_Interp *interp,
        const char *zCmd,
        size_t nCmd);
    int (*th8_AutoPathSearch)(Th8_Interp *interp, char *zAuto, size_t nAuto);
    const char *(*th8_GetCurrentNamespace)(Th8_Interp *interp);
    int (*th8_FindNamespace)(
        Th8_Interp *interp,
        const char *zName,
        size_t nName,
        int bCreate);
    int (*th8_DeleteNamespace)(
        Th8_Interp *interp,
        const char *zName,
        size_t nName);
    int (*th8_NsEval)(
        Th8_Interp *interp,
        const char *zNs,
        size_t nNs,
        const char *zScript,
        size_t nScript);
    int (*th8_ListAppendNsChildren)(
        Th8_Interp *interp,
        const char *zNs,
        size_t nNs,
        char **pz,
        size_t *pn);
    int (*th8_NsExport)(
        Th8_Interp *interp,
        const char *zNs,
        size_t nNs,
        const char *zPattern,
        size_t nPattern);
    int (*th8_NsImport)(
        Th8_Interp *interp,
        const char *zPattern,
        size_t nPattern,
        int bForce);
    void (*th8_PushSourceName)(
        Th8_Interp *interp,
        const char *zName,
        size_t nName);
    void (*th8_PopSourceName)(Th8_Interp *interp);
    const char *(*th8_GetSourceName)(Th8_Interp *interp, size_t *pnName);
    int (*th8_GetTimeMs)(Th8_Interp *interp, th8_int64_t *pMs);
    int (*th8_GetTimeUs)(Th8_Interp *interp, th8_int64_t *pUs);
    void (*th8_Sleep)(Th8_Interp *interp, int nMs);
    int (*th8_GetPid)(Th8_Interp *interp);
    int (*th8_GetParentPid)(Th8_Interp *interp);
    th8_uint64_t (*th8_GetThreadId)(Th8_Interp *interp);
    char *(*th8_GetEnv)(Th8_Interp *interp, const char *zName);
    int (*th8_KeyValue)(
        Th8_Interp *interp,
        int op,
        const char *zName,
        size_t nName,
        const char *zValue,
        size_t nValue);
    int (*th8_SetPlatformContext)(
        Th8_Interp *interp,
        Th8_PlatformFunc xCallback,
        void *pCtx);
    int (*th8_GetPlatformContext)(
        Th8_Interp *interp,
        Th8_PlatformFunc xCallback,
        void **ppCtx);
    int (*th8_RandomBytes)(Th8_Interp *interp, void *pBuf, size_t nByte);
    int (*th8_DnsResolve)(
        Th8_Interp *interp,
        const char *zName,
        size_t nName,
        int eType,
        Th8_DnsResult **ppResult);
    void (*th8_DnsResolveFree)(Th8_Interp *interp, Th8_DnsResult *pResult);
    char *(*th8_GetExePath)(Th8_Interp *interp);
    const Th8_Platform *(*th8_GetPlatform)(Th8_Interp *interp);
    size_t (*th8_Strlen)(Th8_Interp *interp, const char *z);
    char *(*th8_Strdup)(Th8_Interp *interp, const char *z, size_t n);
    int (*th8_Memcmp)(
        Th8_Interp *interp,
        const void *a,
        const void *b,
        size_t n);
    void *(*th8_Memcpy)(
        Th8_Interp *interp,
        void *dst,
        const void *src,
        size_t n);
    void *(*th8_Memset)(Th8_Interp *interp, void *dst, int c, size_t n);
    int (*th8_Utf8Decode)(const char *z, size_t n, int *pnByte);
    int (*th8_Utf8Encode)(int codepoint, char *z);
    int (*th8_Utf8Len)(const char *z, size_t n);
    const char *(*th8_Utf8Advance)(const char *z, size_t n, int nChar);
    const char *(*th8_Utf8Index)(const char *z, size_t n, int iChar);
    int (*th8_Utf8Validate)(const char *z, size_t n, int *piOffset);
    int (*th8_ByteToUtf16Col)(const char *zLine, size_t nLine, int nByte);
#if !defined(_WIN32) && !defined(WIN32)
    const Th8_Platform *(*th8_GetPosixPlatform)(void);
#else
    void *th8_GetPosixPlatform;
#endif
#if defined(_WIN32) || defined(WIN32)
    const Th8_Platform *(*th8_GetWin32Platform)(void);
#else
    void *th8_GetWin32Platform;
#endif
#if defined(__APPLE__)
    const Th8_Platform *(*th8_GetMacOSPlatform)(void);
#else
    void *th8_GetMacOSPlatform;
#endif
#if defined(TH8_PLATFORM_IOS)
    const Th8_Platform *(*th8_GetIosPlatform)(void);
#else
    void *th8_GetIosPlatform;
#endif
#if defined(TH8_PLATFORM_ANDROID)
    const Th8_Platform *(*th8_GetAndroidPlatform)(void);
#else
    void *th8_GetAndroidPlatform;
#endif
#if defined(TH8_ENABLE_LIBCURL)
    const Th8_Platform *(*th8_GetCurlPlatform)(void);
#else
    void *th8_GetCurlPlatform;
#endif
    const Th8_Platform *(*th8_GetNullIoPlatform)(void);
    const Th8_Platform *(*th8_GetLibcPlatform)(void);
    const Th8_Platform *(*th8_GetEnvPlatform)(void);
#if defined(TH8_USE_MIMALLOC)
    const Th8_Platform *(*th8_GetMimallocPlatform)(void);
#else
    void *th8_GetMimallocPlatform;
#endif
#if defined(TH8_PLATFORM_COSMOPOLITAN)
    const Th8_Platform *(*th8_GetCosmopolitanPlatform)(void);
#else
    void *th8_GetCosmopolitanPlatform;
#endif
    const Th8_Platform *(*th8_GetMemPlatform)(void);
    int (*th8_UseDefaultPlatform)(Th8_Platform *pPlatform);
#if defined(TH8_ENABLE_FAULT_INJECTION)
    void (*th8_FaultConfigInit)(Th8_FaultConfig *pCfg);
#else
    void *th8_FaultConfigInit;
#endif
#if defined(TH8_ENABLE_FAULT_INJECTION)
    int (*th8_FaultInstall)(
        Th8_Interp *interp,
        Th8_FaultConfig *pConfig,
        Th8_FaultCtx *pCtx);
#else
    void *th8_FaultInstall;
#endif
#if defined(TH8_ENABLE_FAULT_INJECTION)
    int (*th8_FaultUninstall)(Th8_Interp *interp, Th8_FaultCtx *pCtx);
#else
    void *th8_FaultUninstall;
#endif
#if defined(TH8_ENABLE_FAULT_INJECTION)
    size_t (*th8_FaultCtxSize)(void);
#else
    void *th8_FaultCtxSize;
#endif
    int (*th8_RegisterLanguage)(Th8_Interp *interp);
#if defined(TH8_ENABLE_VARIABLES)
    void (*th8_ResetSecurityArray)(Th8_Interp *interp);
#else
    void *th8_ResetSecurityArray;
#endif
#if defined(TH8_ENABLE_VARIABLES)
    int (*th8_SaveSystemVar)(
        Th8_Interp *interp,
        const char *zArr,
        size_t nArr,
        void **ppSaved);
#else
    void *th8_SaveSystemVar;
#endif
#if defined(TH8_ENABLE_VARIABLES)
    int (*th8_RestoreSystemVar)(
        Th8_Interp *interp,
        const char *zArr,
        size_t nArr,
        void *pSaved);
#else
    void *th8_RestoreSystemVar;
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    int (*th8_AttrFlagsParse)(
        Th8_Interp *interp,
        const char *zText,
        size_t nText,
        int bComplex,
        int bSpace,
        Th8_AfMap *pMap);
#else
    void *th8_AttrFlagsParse;
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    int (*th8_AttrFlagsFormat)(
        Th8_Interp *interp,
        const Th8_AfMap *pMap,
        int bLegacy,
        int bCompact,
        int bSpace,
        int bSort,
        char **pzOut,
        size_t *pnOut);
#else
    void *th8_AttrFlagsFormat;
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    int (*th8_AttrFlagsHave)(
        const Th8_AfMap *pMap,
        th8_int64_t key,
        const char *zHave,
        size_t nHave,
        int bAll,
        int bStrict);
#else
    void *th8_AttrFlagsHave;
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    int (*th8_AttrFlagsChange)(
        Th8_Interp *interp,
        Th8_AfMap *pMap,
        const char *zChange,
        size_t nChange,
        th8_int64_t key);
#else
    void *th8_AttrFlagsChange;
#endif
    void (*th8_SecureZero)(Th8_Interp *interp, void *p, size_t n);
#if defined(TH8_ENABLE_VARIABLES) && defined(TH8_ENABLE_CRYPTOGRAPHY)
    int (*th8_SecureSetMasterKey)(
        Th8_Interp *interp,
        const unsigned char *pKey,
        size_t nKey);
#else
    void *th8_SecureSetMasterKey;
#endif
#if defined(TH8_ENABLE_VARIABLES) && defined(TH8_ENABLE_CRYPTOGRAPHY)
    void (*th8_SecureClearMasterKey)(Th8_Interp *interp);
#else
    void *th8_SecureClearMasterKey;
#endif
#if defined(TH8_ENABLE_VARIABLES) && defined(TH8_ENABLE_CRYPTOGRAPHY)
    int (*th8_EnableSecurePersist)(Th8_Interp *interp, int bEnable);
#else
    void *th8_EnableSecurePersist;
#endif
#if defined(TH8_ENABLE_VARIABLES) && defined(TH8_ENABLE_CRYPTOGRAPHY)
    int (*th8_IsSecurePersistEnabled)(Th8_Interp *interp);
#else
    void *th8_IsSecurePersistEnabled;
#endif
    const char **(*th8_GetCompileOptions)(void);
    void *(*th8_Malloc)(Th8_Interp *interp, size_t nByte);
    void (*th8_Free)(Th8_Interp *interp, void *p);
    void *(*th8_Realloc)(Th8_Interp *interp, void *p, size_t nByte);
    void *(*th8_AttemptMalloc)(Th8_Interp *interp, size_t nByte);
    void *(*th8_AttemptRealloc)(Th8_Interp *interp, void *p, size_t nByte);
    void *(*th8_SafeAlloc)(
        Th8_Interp *interp,
        size_t nByte,
        const char *zFile,
        int nLine);
    void *(*th8_SafeAllocStr)(
        Th8_Interp *interp,
        size_t nLen,
        const char *zFile,
        int nLine);
    void *(*th8_SafeAllocMul)(
        Th8_Interp *interp,
        size_t a,
        size_t b,
        const char *zFile,
        int nLine);
    void *(*th8_SafeAllocAdd)(
        Th8_Interp *interp,
        size_t a,
        size_t b,
        const char *zFile,
        int nLine);
    void *(*th8_SafeAllocMulAdd)(
        Th8_Interp *interp,
        size_t a,
        size_t b,
        size_t c,
        const char *zFile,
        int nLine);
    void *(*th8_SafeRealloc)(
        Th8_Interp *interp,
        void *p,
        size_t nByte,
        const char *zFile,
        int nLine);
    void *(*th8_SafeAttemptRealloc)(
        Th8_Interp *interp,
        void *p,
        size_t nByte,
        const char *zFile,
        int nLine);
    void *(*th8_SafeAllocStrAdd)(
        Th8_Interp *interp,
        size_t k,
        size_t n,
        const char *zFile,
        int nLine);
    void *(*th8_SafeAllocStrMul)(
        Th8_Interp *interp,
        size_t n,
        size_t sz,
        const char *zFile,
        int nLine);
    void *(*th8_SafeAllocMulAdd2)(
        Th8_Interp *interp,
        size_t a,
        size_t b,
        size_t c,
        size_t d,
        size_t e,
        const char *zFile,
        int nLine);
    int (*th8_SafeMul)(Th8_Interp *interp, size_t a, size_t b, size_t *pOut);
    int (*th8_SafeAdd)(Th8_Interp *interp, size_t a, size_t b, size_t *pOut);
#if defined(TH8_ENABLE_LOAD)
    int (*th8_ListAppendLoaded)(Th8_Interp *interp, char **pz, size_t *pn);
#else
    void *th8_ListAppendLoaded;
#endif
#if defined(TH8_BENCHMARKING)
    void (*th8_GetCacheStats)(
        Th8_Interp *interp,
        th8_uint64_t *pnHit,
        th8_uint64_t *pnMiss,
        th8_uint64_t *pnEvict);
#else
    void *th8_GetCacheStats;
#endif
#if defined(TH8_BENCHMARKING)
    void (*th8_ResetCacheStats)(Th8_Interp *interp);
#else
    void *th8_ResetCacheStats;
#endif
    Th8_Value *(*th8_FindInCache)(
        Th8_Interp *interp,
        int cacheType,
        const char *z,
        size_t n);
    int (*th8_GetLastError)(void *interp);
    void (*th8_EmitTrace)(Th8_Interp *interp, const char *zFmt, ...);
    int (*th8_DoesEnvExist)(Th8_Interp *interp, const char *zName);
    int (*th8_RegisterPlugin)(
        Th8_Interp *interp,
        const char *zName,
        Th8_GetCommandsProc xGetCommands);
    int (*th8_UnregisterPlugin)(Th8_Interp *interp, const char *zName);
    int (*th8_ListAppendPlugins)(Th8_Interp *interp, char **pz, size_t *pn);
} Th8StubsTable;

#define TH8_STUBS_MAGIC   (0x54483853)  /* "TH8S" */
#define TH8_STUBS_VERSION (1)

/*
 * Th8_InitStubs --
 *	Retrieve the stubs table from the interpreter.
 *	Returns NULL on failure (version mismatch or stubs
 *	not available).  Extensions must call this before
 *	using any other TH8 API.
 */
const Th8StubsTable *
Th8_InitStubs(Th8_Interp *interp, const char *version, int exact);

/*
 * When USE_TH8_STUBS is defined, all Th8_* calls are
 * redirected through the stubs table.
 */

#ifdef USE_TH8_STUBS

extern const Th8StubsTable *th8StubsPtr;

#  define Th8_MergePlatform       (th8StubsPtr->th8_MergePlatform)
#  define Th8_ClonePlatform       (th8StubsPtr->th8_ClonePlatform)
#  define Th8_FreePlatform        (th8StubsPtr->th8_FreePlatform)
#  define Th8_MergePlatformInterp (th8StubsPtr->th8_MergePlatformInterp)
#  define Th8_Initialize          (th8StubsPtr->th8_Initialize)
#  define Th8_Finalize            (th8StubsPtr->th8_Finalize)
#  define Th8_GetInternalStubs    (th8StubsPtr->th8_GetInternalStubs)
#  define Th8_IntCmpXchg          (th8StubsPtr->th8_IntCmpXchg)
#  define Th8_CreateInterp        (th8StubsPtr->th8_CreateInterp)
#  define Th8_RestoreInterp       (th8StubsPtr->th8_RestoreInterp)
#  define Th8_DeleteInterp        (th8StubsPtr->th8_DeleteInterp)
#  define Th8_Ready               (th8StubsPtr->th8_Ready)
#  define Th8_CancelEval          (th8StubsPtr->th8_CancelEval)
#  define Th8_ThreadInit          (th8StubsPtr->th8_ThreadInit)
#  define Th8_ThreadDone          (th8StubsPtr->th8_ThreadDone)
#  define Th8_CreateAsyncState    (th8StubsPtr->th8_CreateAsyncState)
#  define Th8_FinalizeAsyncState  (th8StubsPtr->th8_FinalizeAsyncState)
#  define Th8_QueueEvent          (th8StubsPtr->th8_QueueEvent)
#  define Th8_DrainQueueEvents    (th8StubsPtr->th8_DrainQueueEvents)
#  define Th8_IsCanceled          (th8StubsPtr->th8_IsCanceled)
#  define Th8_IsBeingUnwound      (th8StubsPtr->th8_IsBeingUnwound)
#  define Th8_ResetCancel         (th8StubsPtr->th8_ResetCancel)
#  define Th8_Exit                (th8StubsPtr->th8_Exit)
#  define Th8_IsExited            (th8StubsPtr->th8_IsExited)
#  define Th8_ResetExit           (th8StubsPtr->th8_ResetExit)
#  define Th8_Freeze              (th8StubsPtr->th8_Freeze)
#  define Th8_Thaw                (th8StubsPtr->th8_Thaw)
#  define Th8_IsSuspended         (th8StubsPtr->th8_IsSuspended)
#  define Th8_SetDebugCallback    (th8StubsPtr->th8_SetDebugCallback)
#  define Th8_SetBreakpoint       (th8StubsPtr->th8_SetBreakpoint)
#  define Th8_ClearBreakpoint     (th8StubsPtr->th8_ClearBreakpoint)
#  define Th8_ClearAllBreakpoints (th8StubsPtr->th8_ClearAllBreakpoints)
#  define Th8_SetStepMode         (th8StubsPtr->th8_SetStepMode)
#  define Th8_GetStepMode         (th8StubsPtr->th8_GetStepMode)
#  define Th8_GetFrameCount       (th8StubsPtr->th8_GetFrameCount)
#  define Th8_GetFrameInfo        (th8StubsPtr->th8_GetFrameInfo)
#  define Th8_EvalAtFrame         (th8StubsPtr->th8_EvalAtFrame)
#  define Th8_CoroCreate          (th8StubsPtr->th8_CoroCreate)
#  define Th8_CoroYield           (th8StubsPtr->th8_CoroYield)
#  define Th8_Eval                (th8StubsPtr->th8_Eval)
#  define Th8_EvalTrusted         (th8StubsPtr->th8_EvalTrusted)
#  define Th8_EvalDownlevel       (th8StubsPtr->th8_EvalDownlevel)
#  if defined(TH8_ENABLE_EXPRESSIONS)
#    define Th8_Expr (th8StubsPtr->th8_Expr)
#  endif
#  define Th8_Complete       (th8StubsPtr->th8_Complete)
#  define Th8_EvalFile       (th8StubsPtr->th8_EvalFile)
#  define Th8_EvalFileAsData (th8StubsPtr->th8_EvalFileAsData)
#  define Th8_NREval         (th8StubsPtr->th8_NREval)
#  define Th8_NRAddCallback  (th8StubsPtr->th8_NRAddCallback)
#  define Th8_NREvalInFrame  (th8StubsPtr->th8_NREvalInFrame)
#  if defined(TH8_ENABLE_VARIABLES)
#    define Th8_ExistsVar (th8StubsPtr->th8_ExistsVar)
#  endif
#  if defined(TH8_ENABLE_VARIABLES)
#    define Th8_ExistsArrayVar (th8StubsPtr->th8_ExistsArrayVar)
#  endif
#  if defined(TH8_ENABLE_VARIABLES)
#    define Th8_GetVar (th8StubsPtr->th8_GetVar)
#  endif
#  if defined(TH8_ENABLE_VARIABLES)
#    define Th8_SetVar (th8StubsPtr->th8_SetVar)
#  endif
#  if defined(TH8_ENABLE_VARIABLES)
#    define Th8_LinkVar (th8StubsPtr->th8_LinkVar)
#  endif
#  if defined(TH8_ENABLE_VARIABLES)
#    define Th8_UnsetVar (th8StubsPtr->th8_UnsetVar)
#  endif
#  define Th8_CreateCommand         (th8StubsPtr->th8_CreateCommand)
#  define Th8_DeleteCommand         (th8StubsPtr->th8_DeleteCommand)
#  define Th8_GetCommandInfo        (th8StubsPtr->th8_GetCommandInfo)
#  define Th8_SetCommandCopy        (th8StubsPtr->th8_SetCommandCopy)
#  define Th8_RenameCommand         (th8StubsPtr->th8_RenameCommand)
#  define Th8_RegisterExpansion     (th8StubsPtr->th8_RegisterExpansion)
#  define Th8_UnregisterExpansion   (th8StubsPtr->th8_UnregisterExpansion)
#  define Th8_FindExpansion         (th8StubsPtr->th8_FindExpansion)
#  define Th8_ListAppendExpansions  (th8StubsPtr->th8_ListAppendExpansions)
#  define Th8_ListAppendBreakpoints (th8StubsPtr->th8_ListAppendBreakpoints)
#  if defined(TH8_ENABLE_EXPRESSIONS)
#    define Th8_CreateMathFunc (th8StubsPtr->th8_CreateMathFunc)
#  endif
#  if defined(TH8_ENABLE_EXPRESSIONS)
#    define Th8_DeleteMathFunc (th8StubsPtr->th8_DeleteMathFunc)
#  endif
#  if defined(TH8_ENABLE_EXPRESSIONS)
#    define Th8_FindMathFunc (th8StubsPtr->th8_FindMathFunc)
#  endif
#  if defined(TH8_ENABLE_EXPRESSIONS)
#    define Th8_ListAppendMathFunctions                                      \
	(th8StubsPtr->th8_ListAppendMathFunctions)
#  endif
#  define Th8_GlobMatch (th8StubsPtr->th8_GlobMatch)
#  define Th8_Subst     (th8StubsPtr->th8_Subst)
#  if defined(TH8_ENABLE_CRYPTOGRAPHY)
#    define Th8_RsaKeyLoad (th8StubsPtr->th8_RsaKeyLoad)
#  endif
#  if defined(TH8_ENABLE_CRYPTOGRAPHY)
#    define Th8_RsaKeyFree (th8StubsPtr->th8_RsaKeyFree)
#  endif
#  if defined(TH8_ENABLE_CRYPTOGRAPHY)
#    define Th8_RsaKeyBitLen (th8StubsPtr->th8_RsaKeyBitLen)
#  endif
#  if defined(TH8_ENABLE_CRYPTOGRAPHY)
#    define Th8_RsaKeyHasPrivate (th8StubsPtr->th8_RsaKeyHasPrivate)
#  endif
#  if defined(TH8_ENABLE_CRYPTOGRAPHY)
#    define Th8_RsaKeyPubExp (th8StubsPtr->th8_RsaKeyPubExp)
#  endif
#  if defined(TH8_ENABLE_CRYPTOGRAPHY)
#    define Th8_RsaKeyModulus (th8StubsPtr->th8_RsaKeyModulus)
#  endif
#  if defined(TH8_ENABLE_CRYPTOGRAPHY)
#    define Th8_RsaKeyPrivExp (th8StubsPtr->th8_RsaKeyPrivExp)
#  endif
#  if defined(TH8_ENABLE_CRYPTOGRAPHY)
#    define Th8_RsaKeyPrime1 (th8StubsPtr->th8_RsaKeyPrime1)
#  endif
#  if defined(TH8_ENABLE_CRYPTOGRAPHY)
#    define Th8_RsaKeyPrime2 (th8StubsPtr->th8_RsaKeyPrime2)
#  endif
#  if defined(TH8_ENABLE_CRYPTOGRAPHY)
#    define Th8_RsaKeyToken (th8StubsPtr->th8_RsaKeyToken)
#  endif
#  if defined(TH8_ENABLE_CRYPTOGRAPHY)
#    define Th8_RsaKeyTokenHex (th8StubsPtr->th8_RsaKeyTokenHex)
#  endif
#  if defined(TH8_ENABLE_CRYPTOGRAPHY)
#    define Th8_HarpySigLoad (th8StubsPtr->th8_HarpySigLoad)
#  endif
#  if defined(TH8_ENABLE_CRYPTOGRAPHY)
#    define Th8_RsaVerify (th8StubsPtr->th8_RsaVerify)
#  endif
#  if defined(TH8_ENABLE_CRYPTOGRAPHY)
#    define Th8_RsaSign (th8StubsPtr->th8_RsaSign)
#  endif
#  if defined(TH8_ENABLE_CRYPTOGRAPHY)
#    define Th8_Sha512Hex (th8StubsPtr->th8_Sha512Hex)
#  endif
#  if defined(TH8_ENABLE_CRYPTOGRAPHY)
#    define Th8_RsaExtractHash (th8StubsPtr->th8_RsaExtractHash)
#  endif
#  if defined(TH8_ENABLE_CRYPTOGRAPHY)
#    define Th8_InstallSignedPolicy (th8StubsPtr->th8_InstallSignedPolicy)
#  endif
#  if defined(TH8_ENABLE_CRYPTOGRAPHY)
#    define Th8_RemoveSignedPolicy (th8StubsPtr->th8_RemoveSignedPolicy)
#  endif
#  if defined(TH8_ENABLE_CRYPTOGRAPHY)
#    define Th8_PolicyPreloadKey (th8StubsPtr->th8_PolicyPreloadKey)
#  endif
#  if defined(TH8_ENABLE_CRYPTOGRAPHY)
#    define Th8_PolicyGetKeyTokens (th8StubsPtr->th8_PolicyGetKeyTokens)
#  endif
#  if defined(TH8_ENABLE_CRYPTOGRAPHY)
#    define Th8_PolicyFindKey (th8StubsPtr->th8_PolicyFindKey)
#  endif
#  if defined(TH8_ENABLE_CRYPTOGRAPHY)
#    define Th8_EnableSignedPolicy (th8StubsPtr->th8_EnableSignedPolicy)
#  endif
#  if defined(TH8_ENABLE_CRYPTOGRAPHY)
#    define Th8_EvalFileAndRsaKeyLoad (th8StubsPtr->th8_EvalFileAndRsaKeyLoad)
#  endif
#  if defined(TH8_ENABLE_CRYPTOGRAPHY)
#    define Th8_GetEmbeddedKeyRoot (th8StubsPtr->th8_GetEmbeddedKeyRoot)
#  endif
#  if defined(TH8_ENABLE_CRYPTOGRAPHY)
#    define Th8_GetEmbeddedKey0 (th8StubsPtr->th8_GetEmbeddedKey0)
#  endif
#  if defined(TH8_ENABLE_CRYPTOGRAPHY)
#    define Th8_GetPublicKeyZero (th8StubsPtr->th8_GetPublicKeyZero)
#  endif
#  if defined(TH8_ENABLE_CRYPTOGRAPHY)
#    define Th8_GetPublicKeyZeroToken (th8StubsPtr->th8_GetPublicKeyZeroToken)
#  endif
#  if defined(TH8_ENABLE_CRYPTOGRAPHY)
#    define Th8_GetPublicKeyRoot (th8StubsPtr->th8_GetPublicKeyRoot)
#  endif
#  if defined(TH8_ENABLE_CRYPTOGRAPHY)
#    define Th8_GetPublicKeyRootToken (th8StubsPtr->th8_GetPublicKeyRootToken)
#  endif
#  if defined(TH8_ENABLE_CRYPTOGRAPHY)
#    define Th8_GetEmbeddedKeyTime (th8StubsPtr->th8_GetEmbeddedKeyTime)
#  endif
#  define Th8_GetEmbeddedKeyring (th8StubsPtr->th8_GetEmbeddedKeyring)
#  if defined(TH8_ENABLE_CRYPTOGRAPHY) && defined(TH8_ENABLE_TEST_KEY)
#    define Th8_GetEmbeddedKeyTest (th8StubsPtr->th8_GetEmbeddedKeyTest)
#  endif
#  if defined(TH8_ENABLE_CRYPTOGRAPHY) && defined(TH8_ENABLE_TEST_KEY)
#    define Th8_GetPublicKeyTest (th8StubsPtr->th8_GetPublicKeyTest)
#  endif
#  if defined(TH8_ENABLE_CRYPTOGRAPHY) && defined(TH8_ENABLE_TEST_KEY)
#    define Th8_GetPublicKeyTestToken (th8StubsPtr->th8_GetPublicKeyTestToken)
#  endif
#  define Th8_Pledge            (th8StubsPtr->th8_Pledge)
#  define Th8_Unveil            (th8StubsPtr->th8_Unveil)
#  define Th8_SetResult         (th8StubsPtr->th8_SetResult)
#  define Th8_SetResultStatic   (th8StubsPtr->th8_SetResultStatic)
#  define Th8_ClearResult       (th8StubsPtr->th8_ClearResult)
#  define Th8_GetResult         (th8StubsPtr->th8_GetResult)
#  define Th8_TakeResult        (th8StubsPtr->th8_TakeResult)
#  define Th8_IsResultSensitive (th8StubsPtr->th8_IsResultSensitive)
#  if defined(TH8_ENABLE_VARIABLES) && defined(TH8_ENABLE_CRYPTOGRAPHY)
#    define Th8_MarkResultSensitive (th8StubsPtr->th8_MarkResultSensitive)
#  endif
#  if defined(TH8_ENABLE_CRYPTOGRAPHY)
#    define Th8_SetResultSensitive (th8StubsPtr->th8_SetResultSensitive)
#  endif
#  define Th8_ErrorMessage     (th8StubsPtr->th8_ErrorMessage)
#  define Th8_SetResultInt     (th8StubsPtr->th8_SetResultInt)
#  define Th8_SetResultWideInt (th8StubsPtr->th8_SetResultWideInt)
#  define Th8_SetResultDouble  (th8StubsPtr->th8_SetResultDouble)
#  define Th8_GetErrorLine     (th8StubsPtr->th8_GetErrorLine)
#  define Th8_GetEvalDepth     (th8StubsPtr->th8_GetEvalDepth)
#  define Th8_SetErrorLine     (th8StubsPtr->th8_SetErrorLine)
#  define Th8_GetLine          (th8StubsPtr->th8_GetLine)
#  define Th8_SetStepLimit     (th8StubsPtr->th8_SetStepLimit)
#  define Th8_GetStepLimit     (th8StubsPtr->th8_GetStepLimit)
#  define Th8_GetStepCount     (th8StubsPtr->th8_GetStepCount)
#  define Th8_ResetStepCount   (th8StubsPtr->th8_ResetStepCount)
#  define Th8_SetStepCount     (th8StubsPtr->th8_SetStepCount)
#  define Th8_SetResultLimit   (th8StubsPtr->th8_SetResultLimit)
#  define Th8_GetResultLimit   (th8StubsPtr->th8_GetResultLimit)
#  if defined(TH8_ENABLE_BIGINT)
#    define Th8_EnableBigint (th8StubsPtr->th8_EnableBigint)
#  endif
#  if defined(TH8_ENABLE_BIGINT)
#    define Th8_IsBigintEnabled (th8StubsPtr->th8_IsBigintEnabled)
#  endif
#  define Th8_GetExprFeatures  (th8StubsPtr->th8_GetExprFeatures)
#  define Th8_SetExprFeatures  (th8StubsPtr->th8_SetExprFeatures)
#  define Th8_SetOverflowCheck (th8StubsPtr->th8_SetOverflowCheck)
#  define Th8_GetOverflowCheck (th8StubsPtr->th8_GetOverflowCheck)
#  define Th8_SetAllocLimit    (th8StubsPtr->th8_SetAllocLimit)
#  define Th8_GetAllocLimit    (th8StubsPtr->th8_GetAllocLimit)
#  define Th8_GetAllocBytes    (th8StubsPtr->th8_GetAllocBytes)
#  if defined(TH8_ENABLE_LOAD)
#    define Th8_EnableLoad (th8StubsPtr->th8_EnableLoad)
#  endif
#  if defined(TH8_ENABLE_LOAD)
#    define Th8_IsLoadEnabled (th8StubsPtr->th8_IsLoadEnabled)
#  endif
#  define Th8_EnableSignedOnly    (th8StubsPtr->th8_EnableSignedOnly)
#  define Th8_IsSignedOnlyEnabled (th8StubsPtr->th8_IsSignedOnlyEnabled)
#  if defined(TH8_ENABLE_CRYPTOGRAPHY)
#    define Th8_SaveSignedOnly (th8StubsPtr->th8_SaveSignedOnly)
#  endif
#  if defined(TH8_ENABLE_CRYPTOGRAPHY)
#    define Th8_RestoreSignedOnly (th8StubsPtr->th8_RestoreSignedOnly)
#  endif
#  if defined(TH8_ENABLE_VARIABLES)
#    define Th8_DeclareSystemVar (th8StubsPtr->th8_DeclareSystemVar)
#  endif
#  if defined(TH8_ENABLE_VARIABLES)
#    define Th8_IsSystemVar (th8StubsPtr->th8_IsSystemVar)
#  endif
#  if defined(TH8_ENABLE_LOAD)
#    define Th8_Load (th8StubsPtr->th8_Load)
#  endif
#  if defined(TH8_ENABLE_LOAD)
#    define Th8_EnableUnload (th8StubsPtr->th8_EnableUnload)
#  endif
#  if defined(TH8_ENABLE_LOAD)
#    define Th8_Unload (th8StubsPtr->th8_Unload)
#  endif
#  define Th8_SetPolicyCallback (th8StubsPtr->th8_SetPolicyCallback)
#  if defined(TH8_ENABLE_LOAD)
#    define Th8_SetPreLoadCallback (th8StubsPtr->th8_SetPreLoadCallback)
#  endif
#  define Th8_GetPolicyCallback  (th8StubsPtr->th8_GetPolicyCallback)
#  define Th8_GetFrameObjv       (th8StubsPtr->th8_GetFrameObjv)
#  define Th8_StringAppend       (th8StubsPtr->th8_StringAppend)
#  define Th8_ListAppend         (th8StubsPtr->th8_ListAppend)
#  define Th8_SplitList          (th8StubsPtr->th8_SplitList)
#  define Th8_ToInt              (th8StubsPtr->th8_ToInt)
#  define Th8_ToBoolean          (th8StubsPtr->th8_ToBoolean)
#  define Th8_ToWideInt          (th8StubsPtr->th8_ToWideInt)
#  define Th8_ToDouble           (th8StubsPtr->th8_ToDouble)
#  define Th8_ListAppendCommands (th8StubsPtr->th8_ListAppendCommands)
#  define Th8_ListAppendCommandsMatching                                     \
      (th8StubsPtr->th8_ListAppendCommandsMatching)
#  if defined(TH8_ENABLE_VARIABLES)
#    define Th8_ListAppendVariables (th8StubsPtr->th8_ListAppendVariables)
#  endif
#  if defined(TH8_ENABLE_VARIABLES)
#    define Th8_ListAppendNsVariables (th8StubsPtr->th8_ListAppendNsVariables)
#  endif
#  if defined(TH8_ENABLE_VARIABLES)
#    define Th8_ListAppendGlobalVariables                                    \
	(th8StubsPtr->th8_ListAppendGlobalVariables)
#  endif
#  if defined(TH8_ENABLE_VARIABLES)
#    define Th8_ListAppendVarLinks (th8StubsPtr->th8_ListAppendVarLinks)
#  endif
#  if defined(TH8_ENABLE_VARIABLES)
#    define Th8_ListAppendArray (th8StubsPtr->th8_ListAppendArray)
#  endif
#  define Th8_WrongNumArgs   (th8StubsPtr->th8_WrongNumArgs)
#  define Th8_CallSubCommand (th8StubsPtr->th8_CallSubCommand)
#  define Th8_ReportTaint    (th8StubsPtr->th8_ReportTaint)
#  define Th8_Input          (th8StubsPtr->th8_Input)
#  define Th8_Output         (th8StubsPtr->th8_Output)
#  define Th8_OutputError    (th8StubsPtr->th8_OutputError)
#  if defined(TH8_PLUGIN_IO)
#    define Th8_GetInput (th8StubsPtr->th8_GetInput)
#  endif
#  if defined(TH8_PLUGIN_IO)
#    define Th8_RedirectInput (th8StubsPtr->th8_RedirectInput)
#  endif
#  if defined(TH8_PLUGIN_IO)
#    define Th8_GetOutput (th8StubsPtr->th8_GetOutput)
#  endif
#  if defined(TH8_PLUGIN_IO)
#    define Th8_RedirectOutput (th8StubsPtr->th8_RedirectOutput)
#  endif
#  if defined(TH8_PLUGIN_IO)
#    define Th8_GetErrorOutput (th8StubsPtr->th8_GetErrorOutput)
#  endif
#  if defined(TH8_PLUGIN_IO)
#    define Th8_RedirectErrorOutput (th8StubsPtr->th8_RedirectErrorOutput)
#  endif
#  define Th8_GetData              (th8StubsPtr->th8_GetData)
#  define Th8_DataExists           (th8StubsPtr->th8_DataExists)
#  define Th8_NormalizePath        (th8StubsPtr->th8_NormalizePath)
#  define Th8_GetCwd               (th8StubsPtr->th8_GetCwd)
#  define Th8_SetCwd               (th8StubsPtr->th8_SetCwd)
#  define Th8_GetRealPath          (th8StubsPtr->th8_GetRealPath)
#  define Th8_GetRootPath          (th8StubsPtr->th8_GetRootPath)
#  define Th8_SameFile             (th8StubsPtr->th8_SameFile)
#  define Th8_SetBasePath          (th8StubsPtr->th8_SetBasePath)
#  define Th8_GetBasePath          (th8StubsPtr->th8_GetBasePath)
#  define Th8_HashNew              (th8StubsPtr->th8_HashNew)
#  define Th8_HashDelete           (th8StubsPtr->th8_HashDelete)
#  define Th8_HashIterate          (th8StubsPtr->th8_HashIterate)
#  define Th8_HashIterateOrdered   (th8StubsPtr->th8_HashIterateOrdered)
#  define Th8_HashFind             (th8StubsPtr->th8_HashFind)
#  define Th8_HashRemove           (th8StubsPtr->th8_HashRemove)
#  define th8SeedHash              (th8StubsPtr->th8SeedHash)
#  define Th8_GetPackageHash       (th8StubsPtr->th8_GetPackageHash)
#  define Th8_GetMathFuncHash      (th8StubsPtr->th8_GetMathFuncHash)
#  define Th8_IterateArraySearches (th8StubsPtr->th8_IterateArraySearches)
#  define Th8_GetPackageUnknown    (th8StubsPtr->th8_GetPackageUnknown)
#  define Th8_SetPackageUnknown    (th8StubsPtr->th8_SetPackageUnknown)
#  define Th8_AutoPathSearch       (th8StubsPtr->th8_AutoPathSearch)
#  define Th8_GetCurrentNamespace  (th8StubsPtr->th8_GetCurrentNamespace)
#  define Th8_FindNamespace        (th8StubsPtr->th8_FindNamespace)
#  define Th8_DeleteNamespace      (th8StubsPtr->th8_DeleteNamespace)
#  define Th8_NsEval               (th8StubsPtr->th8_NsEval)
#  define Th8_ListAppendNsChildren (th8StubsPtr->th8_ListAppendNsChildren)
#  define Th8_NsExport             (th8StubsPtr->th8_NsExport)
#  define Th8_NsImport             (th8StubsPtr->th8_NsImport)
#  define Th8_PushSourceName       (th8StubsPtr->th8_PushSourceName)
#  define Th8_PopSourceName        (th8StubsPtr->th8_PopSourceName)
#  define Th8_GetSourceName        (th8StubsPtr->th8_GetSourceName)
#  define Th8_GetTimeMs            (th8StubsPtr->th8_GetTimeMs)
#  define Th8_GetTimeUs            (th8StubsPtr->th8_GetTimeUs)
#  define Th8_Sleep                (th8StubsPtr->th8_Sleep)
#  define Th8_GetPid               (th8StubsPtr->th8_GetPid)
#  define Th8_GetParentPid         (th8StubsPtr->th8_GetParentPid)
#  define Th8_GetThreadId          (th8StubsPtr->th8_GetThreadId)
#  define Th8_GetEnv               (th8StubsPtr->th8_GetEnv)
#  define Th8_KeyValue             (th8StubsPtr->th8_KeyValue)
#  define Th8_SetPlatformContext   (th8StubsPtr->th8_SetPlatformContext)
#  define Th8_GetPlatformContext   (th8StubsPtr->th8_GetPlatformContext)
#  define Th8_RandomBytes          (th8StubsPtr->th8_RandomBytes)
#  define Th8_DnsResolve           (th8StubsPtr->th8_DnsResolve)
#  define Th8_DnsResolveFree       (th8StubsPtr->th8_DnsResolveFree)
#  define Th8_GetExePath           (th8StubsPtr->th8_GetExePath)
#  define Th8_GetPlatform          (th8StubsPtr->th8_GetPlatform)
#  define Th8_Strlen               (th8StubsPtr->th8_Strlen)
#  define Th8_Strdup               (th8StubsPtr->th8_Strdup)
#  define Th8_Memcmp               (th8StubsPtr->th8_Memcmp)
#  define Th8_Memcpy               (th8StubsPtr->th8_Memcpy)
#  define Th8_Memset               (th8StubsPtr->th8_Memset)
#  define Th8_Utf8Decode           (th8StubsPtr->th8_Utf8Decode)
#  define Th8_Utf8Encode           (th8StubsPtr->th8_Utf8Encode)
#  define Th8_Utf8Len              (th8StubsPtr->th8_Utf8Len)
#  define Th8_Utf8Advance          (th8StubsPtr->th8_Utf8Advance)
#  define Th8_Utf8Index            (th8StubsPtr->th8_Utf8Index)
#  define Th8_Utf8Validate         (th8StubsPtr->th8_Utf8Validate)
#  define Th8_ByteToUtf16Col       (th8StubsPtr->th8_ByteToUtf16Col)
#  if !defined(_WIN32) && !defined(WIN32)
#    define Th8_GetPosixPlatform (th8StubsPtr->th8_GetPosixPlatform)
#  endif
#  if defined(_WIN32) || defined(WIN32)
#    define Th8_GetWin32Platform (th8StubsPtr->th8_GetWin32Platform)
#  endif
#  if defined(__APPLE__)
#    define Th8_GetMacOSPlatform (th8StubsPtr->th8_GetMacOSPlatform)
#  endif
#  if defined(TH8_PLATFORM_IOS)
#    define Th8_GetIosPlatform (th8StubsPtr->th8_GetIosPlatform)
#  endif
#  if defined(TH8_PLATFORM_ANDROID)
#    define Th8_GetAndroidPlatform (th8StubsPtr->th8_GetAndroidPlatform)
#  endif
#  if defined(TH8_ENABLE_LIBCURL)
#    define Th8_GetCurlPlatform (th8StubsPtr->th8_GetCurlPlatform)
#  endif
#  define Th8_GetNullIoPlatform (th8StubsPtr->th8_GetNullIoPlatform)
#  define Th8_GetLibcPlatform   (th8StubsPtr->th8_GetLibcPlatform)
#  define Th8_GetEnvPlatform    (th8StubsPtr->th8_GetEnvPlatform)
#  if defined(TH8_USE_MIMALLOC)
#    define Th8_GetMimallocPlatform (th8StubsPtr->th8_GetMimallocPlatform)
#  endif
#  if defined(TH8_PLATFORM_COSMOPOLITAN)
#    define Th8_GetCosmopolitanPlatform                                      \
	(th8StubsPtr->th8_GetCosmopolitanPlatform)
#  endif
#  define Th8_GetMemPlatform     (th8StubsPtr->th8_GetMemPlatform)
#  define Th8_UseDefaultPlatform (th8StubsPtr->th8_UseDefaultPlatform)
#  if defined(TH8_ENABLE_FAULT_INJECTION)
#    define Th8_FaultConfigInit (th8StubsPtr->th8_FaultConfigInit)
#  endif
#  if defined(TH8_ENABLE_FAULT_INJECTION)
#    define Th8_FaultInstall (th8StubsPtr->th8_FaultInstall)
#  endif
#  if defined(TH8_ENABLE_FAULT_INJECTION)
#    define Th8_FaultUninstall (th8StubsPtr->th8_FaultUninstall)
#  endif
#  if defined(TH8_ENABLE_FAULT_INJECTION)
#    define Th8_FaultCtxSize (th8StubsPtr->th8_FaultCtxSize)
#  endif
#  define Th8_RegisterLanguage (th8StubsPtr->th8_RegisterLanguage)
#  if defined(TH8_ENABLE_VARIABLES)
#    define Th8_ResetSecurityArray (th8StubsPtr->th8_ResetSecurityArray)
#  endif
#  if defined(TH8_ENABLE_VARIABLES)
#    define Th8_SaveSystemVar (th8StubsPtr->th8_SaveSystemVar)
#  endif
#  if defined(TH8_ENABLE_VARIABLES)
#    define Th8_RestoreSystemVar (th8StubsPtr->th8_RestoreSystemVar)
#  endif
#  if defined(TH8_ENABLE_CRYPTOGRAPHY)
#    define Th8_AttrFlagsParse (th8StubsPtr->th8_AttrFlagsParse)
#  endif
#  if defined(TH8_ENABLE_CRYPTOGRAPHY)
#    define Th8_AttrFlagsFormat (th8StubsPtr->th8_AttrFlagsFormat)
#  endif
#  if defined(TH8_ENABLE_CRYPTOGRAPHY)
#    define Th8_AttrFlagsHave (th8StubsPtr->th8_AttrFlagsHave)
#  endif
#  if defined(TH8_ENABLE_CRYPTOGRAPHY)
#    define Th8_AttrFlagsChange (th8StubsPtr->th8_AttrFlagsChange)
#  endif
#  define Th8_SecureZero (th8StubsPtr->th8_SecureZero)
#  if defined(TH8_ENABLE_VARIABLES) && defined(TH8_ENABLE_CRYPTOGRAPHY)
#    define Th8_SecureSetMasterKey (th8StubsPtr->th8_SecureSetMasterKey)
#  endif
#  if defined(TH8_ENABLE_VARIABLES) && defined(TH8_ENABLE_CRYPTOGRAPHY)
#    define Th8_SecureClearMasterKey (th8StubsPtr->th8_SecureClearMasterKey)
#  endif
#  if defined(TH8_ENABLE_VARIABLES) && defined(TH8_ENABLE_CRYPTOGRAPHY)
#    define Th8_EnableSecurePersist (th8StubsPtr->th8_EnableSecurePersist)
#  endif
#  if defined(TH8_ENABLE_VARIABLES) && defined(TH8_ENABLE_CRYPTOGRAPHY)
#    define Th8_IsSecurePersistEnabled                                       \
	(th8StubsPtr->th8_IsSecurePersistEnabled)
#  endif
#  define Th8_GetCompileOptions  (th8StubsPtr->th8_GetCompileOptions)
#  define Th8_Malloc             (th8StubsPtr->th8_Malloc)
#  define Th8_Free               (th8StubsPtr->th8_Free)
#  define Th8_Realloc            (th8StubsPtr->th8_Realloc)
#  define Th8_AttemptMalloc      (th8StubsPtr->th8_AttemptMalloc)
#  define Th8_AttemptRealloc     (th8StubsPtr->th8_AttemptRealloc)
#  define Th8_SafeAlloc          (th8StubsPtr->th8_SafeAlloc)
#  define Th8_SafeAllocStr       (th8StubsPtr->th8_SafeAllocStr)
#  define Th8_SafeAllocMul       (th8StubsPtr->th8_SafeAllocMul)
#  define Th8_SafeAllocAdd       (th8StubsPtr->th8_SafeAllocAdd)
#  define Th8_SafeAllocMulAdd    (th8StubsPtr->th8_SafeAllocMulAdd)
#  define Th8_SafeRealloc        (th8StubsPtr->th8_SafeRealloc)
#  define Th8_SafeAttemptRealloc (th8StubsPtr->th8_SafeAttemptRealloc)
#  define Th8_SafeAllocStrAdd    (th8StubsPtr->th8_SafeAllocStrAdd)
#  define Th8_SafeAllocStrMul    (th8StubsPtr->th8_SafeAllocStrMul)
#  define Th8_SafeAllocMulAdd2   (th8StubsPtr->th8_SafeAllocMulAdd2)
#  define Th8_SafeMul            (th8StubsPtr->th8_SafeMul)
#  define Th8_SafeAdd            (th8StubsPtr->th8_SafeAdd)
#  if defined(TH8_ENABLE_LOAD)
#    define Th8_ListAppendLoaded (th8StubsPtr->th8_ListAppendLoaded)
#  endif
#  if defined(TH8_BENCHMARKING)
#    define Th8_GetCacheStats (th8StubsPtr->th8_GetCacheStats)
#  endif
#  if defined(TH8_BENCHMARKING)
#    define Th8_ResetCacheStats (th8StubsPtr->th8_ResetCacheStats)
#  endif
#  define Th8_FindInCache       (th8StubsPtr->th8_FindInCache)
#  define Th8_GetLastError      (th8StubsPtr->th8_GetLastError)
#  define Th8_EmitTrace         (th8StubsPtr->th8_EmitTrace)
#  define Th8_DoesEnvExist      (th8StubsPtr->th8_DoesEnvExist)
#  define Th8_RegisterPlugin    (th8StubsPtr->th8_RegisterPlugin)
#  define Th8_UnregisterPlugin  (th8StubsPtr->th8_UnregisterPlugin)
#  define Th8_ListAppendPlugins (th8StubsPtr->th8_ListAppendPlugins)

#endif /* USE_TH8_STUBS */

#endif /* TH8_DECLS_H */
