/*
 * th8StubInit.c --
 *
 *	TH8 stubs table static initializer.  Auto-generated by
 *	tools/mkstubs.tcl.  DO NOT EDIT BY HAND.
 *
 *	This file is compiled into the TH8 core library (not the
 *	stubs library).  It provides the static Th8StubsTable
 *	populated with pointers to all public API functions.
 *
 * Copyright (c) 2026 by Joe Mistachkin.  All rights reserved.
 *
 * See the file "license.terms" for information on usage and redistribution of
 * this file, and for a DISCLAIMER OF ALL WARRANTIES.
 */

#include "th8.h"
#include "th8Decls.h"

const Th8StubsTable th8StubsTableData = {
    TH8_STUBS_MAGIC,
    TH8_STUBS_VERSION,
    Th8_MergePlatform,
    Th8_ClonePlatform,
    Th8_FreePlatform,
    Th8_MergePlatformInterp,
    Th8_Initialize,
    Th8_Finalize,
    Th8_GetInternalStubs,
    Th8_IntCmpXchg,
    Th8_CreateInterp,
    Th8_RestoreInterp,
    Th8_DeleteInterp,
    Th8_Ready,
    Th8_CancelEval,
    Th8_ThreadInit,
    Th8_ThreadDone,
    Th8_CreateAsyncState,
    Th8_FinalizeAsyncState,
    Th8_QueueEvent,
    Th8_DrainQueueEvents,
    Th8_IsCanceled,
    Th8_IsBeingUnwound,
    Th8_ResetCancel,
    Th8_Exit,
    Th8_IsExited,
    Th8_ResetExit,
    Th8_Freeze,
    Th8_Thaw,
    Th8_IsSuspended,
    Th8_SetDebugCallback,
    Th8_SetBreakpoint,
    Th8_ClearBreakpoint,
    Th8_ClearAllBreakpoints,
    Th8_SetStepMode,
    Th8_GetStepMode,
    Th8_GetFrameCount,
    Th8_GetFrameInfo,
    Th8_EvalAtFrame,
    Th8_CoroCreate,
    Th8_CoroYield,
    Th8_Eval,
    Th8_EvalTrusted,
    Th8_EvalDownlevel,
#if defined(TH8_ENABLE_EXPRESSIONS)
    Th8_Expr,
#else
    0,
#endif
    Th8_Complete,
    Th8_EvalFile,
    Th8_EvalFileAsData,
    Th8_NREval,
    Th8_NRAddCallback,
    Th8_NREvalInFrame,
#if defined(TH8_ENABLE_VARIABLES)
    Th8_ExistsVar,
#else
    0,
#endif
#if defined(TH8_ENABLE_VARIABLES)
    Th8_ExistsArrayVar,
#else
    0,
#endif
#if defined(TH8_ENABLE_VARIABLES)
    Th8_GetVar,
#else
    0,
#endif
#if defined(TH8_ENABLE_VARIABLES)
    Th8_SetVar,
#else
    0,
#endif
#if defined(TH8_ENABLE_VARIABLES)
    Th8_LinkVar,
#else
    0,
#endif
#if defined(TH8_ENABLE_VARIABLES)
    Th8_UnsetVar,
#else
    0,
#endif
    Th8_CreateCommand,
    Th8_DeleteCommand,
    Th8_GetCommandInfo,
    Th8_SetCommandCopy,
    Th8_RenameCommand,
    Th8_RegisterExpansion,
    Th8_UnregisterExpansion,
    Th8_FindExpansion,
    Th8_ListAppendExpansions,
    Th8_ListAppendBreakpoints,
#if defined(TH8_ENABLE_EXPRESSIONS)
    Th8_CreateMathFunc,
#else
    0,
#endif
#if defined(TH8_ENABLE_EXPRESSIONS)
    Th8_DeleteMathFunc,
#else
    0,
#endif
#if defined(TH8_ENABLE_EXPRESSIONS)
    Th8_FindMathFunc,
#else
    0,
#endif
#if defined(TH8_ENABLE_EXPRESSIONS)
    Th8_ListAppendMathFunctions,
#else
    0,
#endif
    Th8_GlobMatch,
    Th8_Subst,
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    Th8_RsaKeyLoad,
#else
    0,
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    Th8_RsaKeyFree,
#else
    0,
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    Th8_RsaKeyBitLen,
#else
    0,
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    Th8_RsaKeyHasPrivate,
#else
    0,
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    Th8_RsaKeyPubExp,
#else
    0,
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    Th8_RsaKeyModulus,
#else
    0,
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    Th8_RsaKeyPrivExp,
#else
    0,
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    Th8_RsaKeyPrime1,
#else
    0,
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    Th8_RsaKeyPrime2,
#else
    0,
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    Th8_RsaKeyToken,
#else
    0,
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    Th8_RsaKeyTokenHex,
#else
    0,
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    Th8_HarpySigLoad,
#else
    0,
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    Th8_RsaVerify,
#else
    0,
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    Th8_RsaSign,
#else
    0,
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    Th8_Sha512Hex,
#else
    0,
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    Th8_RsaExtractHash,
#else
    0,
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    Th8_InstallSignedPolicy,
#else
    0,
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    Th8_RemoveSignedPolicy,
#else
    0,
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    Th8_PolicyPreloadKey,
#else
    0,
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    Th8_PolicyGetKeyTokens,
#else
    0,
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    Th8_PolicyFindKey,
#else
    0,
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    Th8_EnableSignedPolicy,
#else
    0,
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    Th8_EvalFileAndRsaKeyLoad,
#else
    0,
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    Th8_GetEmbeddedKeyRoot,
#else
    0,
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    Th8_GetEmbeddedKey0,
#else
    0,
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    Th8_GetPublicKeyZero,
#else
    0,
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    Th8_GetPublicKeyZeroToken,
#else
    0,
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    Th8_GetPublicKeyRoot,
#else
    0,
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    Th8_GetPublicKeyRootToken,
#else
    0,
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    Th8_GetEmbeddedKeyTime,
#else
    0,
#endif
    Th8_GetEmbeddedKeyring,
#if defined(TH8_ENABLE_CRYPTOGRAPHY) && defined(TH8_ENABLE_TEST_KEY)
    Th8_GetEmbeddedKeyTest,
#else
    0,
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY) && defined(TH8_ENABLE_TEST_KEY)
    Th8_GetPublicKeyTest,
#else
    0,
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY) && defined(TH8_ENABLE_TEST_KEY)
    Th8_GetPublicKeyTestToken,
#else
    0,
#endif
    Th8_Pledge,
    Th8_Unveil,
    Th8_SetResult,
    Th8_SetResultStatic,
    Th8_ClearResult,
    Th8_GetResult,
    Th8_TakeResult,
    Th8_IsResultSensitive,
#if defined(TH8_ENABLE_VARIABLES) && defined(TH8_ENABLE_CRYPTOGRAPHY)
    Th8_MarkResultSensitive,
#else
    0,
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    Th8_SetResultSensitive,
#else
    0,
#endif
    Th8_ErrorMessage,
    Th8_SetResultInt,
    Th8_SetResultWideInt,
    Th8_SetResultDouble,
    Th8_GetErrorLine,
    Th8_GetEvalDepth,
    Th8_SetErrorLine,
    Th8_GetLine,
    Th8_SetStepLimit,
    Th8_GetStepLimit,
    Th8_GetStepCount,
    Th8_ResetStepCount,
    Th8_SetStepCount,
    Th8_SetResultLimit,
    Th8_GetResultLimit,
#if defined(TH8_ENABLE_BIGINT)
    Th8_EnableBigint,
#else
    0,
#endif
#if defined(TH8_ENABLE_BIGINT)
    Th8_IsBigintEnabled,
#else
    0,
#endif
    Th8_GetExprFeatures,
    Th8_SetExprFeatures,
    Th8_SetOverflowCheck,
    Th8_GetOverflowCheck,
    Th8_SetAllocLimit,
    Th8_GetAllocLimit,
    Th8_GetAllocBytes,
#if defined(TH8_ENABLE_LOAD)
    Th8_EnableLoad,
#else
    0,
#endif
#if defined(TH8_ENABLE_LOAD)
    Th8_IsLoadEnabled,
#else
    0,
#endif
    Th8_EnableSignedOnly,
    Th8_IsSignedOnlyEnabled,
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    Th8_SaveSignedOnly,
#else
    0,
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    Th8_RestoreSignedOnly,
#else
    0,
#endif
#if defined(TH8_ENABLE_VARIABLES)
    Th8_DeclareSystemVar,
#else
    0,
#endif
#if defined(TH8_ENABLE_VARIABLES)
    Th8_IsSystemVar,
#else
    0,
#endif
#if defined(TH8_ENABLE_LOAD)
    Th8_Load,
#else
    0,
#endif
#if defined(TH8_ENABLE_LOAD)
    Th8_EnableUnload,
#else
    0,
#endif
#if defined(TH8_ENABLE_LOAD)
    Th8_Unload,
#else
    0,
#endif
    Th8_SetPolicyCallback,
#if defined(TH8_ENABLE_LOAD)
    Th8_SetPreLoadCallback,
#else
    0,
#endif
    Th8_GetPolicyCallback,
    Th8_GetFrameObjv,
    Th8_StringAppend,
    Th8_ListAppend,
    Th8_SplitList,
    Th8_ToInt,
    Th8_ToBoolean,
    Th8_ToWideInt,
    Th8_ToDouble,
    Th8_ListAppendCommands,
    Th8_ListAppendCommandsMatching,
#if defined(TH8_ENABLE_VARIABLES)
    Th8_ListAppendVariables,
#else
    0,
#endif
#if defined(TH8_ENABLE_VARIABLES)
    Th8_ListAppendNsVariables,
#else
    0,
#endif
#if defined(TH8_ENABLE_VARIABLES)
    Th8_ListAppendGlobalVariables,
#else
    0,
#endif
#if defined(TH8_ENABLE_VARIABLES)
    Th8_ListAppendVarLinks,
#else
    0,
#endif
#if defined(TH8_ENABLE_VARIABLES)
    Th8_ListAppendArray,
#else
    0,
#endif
    Th8_WrongNumArgs,
    Th8_CallSubCommand,
    Th8_ReportTaint,
    Th8_Input,
    Th8_Output,
    Th8_OutputError,
#if defined(TH8_PLUGIN_IO)
    Th8_GetInput,
#else
    0,
#endif
#if defined(TH8_PLUGIN_IO)
    Th8_RedirectInput,
#else
    0,
#endif
#if defined(TH8_PLUGIN_IO)
    Th8_GetOutput,
#else
    0,
#endif
#if defined(TH8_PLUGIN_IO)
    Th8_RedirectOutput,
#else
    0,
#endif
#if defined(TH8_PLUGIN_IO)
    Th8_GetErrorOutput,
#else
    0,
#endif
#if defined(TH8_PLUGIN_IO)
    Th8_RedirectErrorOutput,
#else
    0,
#endif
    Th8_GetData,
    Th8_DataExists,
    Th8_NormalizePath,
    Th8_GetCwd,
    Th8_SetCwd,
    Th8_GetRealPath,
    Th8_GetRootPath,
    Th8_SameFile,
    Th8_SetBasePath,
    Th8_GetBasePath,
    Th8_HashNew,
    Th8_HashDelete,
    Th8_HashIterate,
    Th8_HashIterateOrdered,
    Th8_HashFind,
    Th8_HashRemove,
    th8SeedHash,
    Th8_GetPackageHash,
    Th8_GetMathFuncHash,
    Th8_IterateArraySearches,
    Th8_GetPackageUnknown,
    Th8_SetPackageUnknown,
    Th8_AutoPathSearch,
    Th8_GetCurrentNamespace,
    Th8_FindNamespace,
    Th8_DeleteNamespace,
    Th8_NsEval,
    Th8_ListAppendNsChildren,
    Th8_NsExport,
    Th8_NsImport,
    Th8_PushSourceName,
    Th8_PopSourceName,
    Th8_GetSourceName,
    Th8_GetTimeMs,
    Th8_GetTimeUs,
    Th8_Sleep,
    Th8_GetPid,
    Th8_GetParentPid,
    Th8_GetThreadId,
    Th8_GetEnv,
    Th8_KeyValue,
    Th8_SetPlatformContext,
    Th8_GetPlatformContext,
    Th8_RandomBytes,
    Th8_DnsResolve,
    Th8_DnsResolveFree,
    Th8_GetExePath,
    Th8_GetPlatform,
    Th8_Strlen,
    Th8_Strdup,
    Th8_Memcmp,
    Th8_Memcpy,
    Th8_Memset,
    Th8_Utf8Decode,
    Th8_Utf8Encode,
    Th8_Utf8Len,
    Th8_Utf8Advance,
    Th8_Utf8Index,
    Th8_Utf8Validate,
    Th8_ByteToUtf16Col,
#if !defined(_WIN32) && !defined(WIN32)
    Th8_GetPosixPlatform,
#else
    0,
#endif
#if defined(_WIN32) || defined(WIN32)
    Th8_GetWin32Platform,
#else
    0,
#endif
#if defined(__APPLE__)
    Th8_GetMacOSPlatform,
#else
    0,
#endif
#if defined(TH8_PLATFORM_IOS)
    Th8_GetIosPlatform,
#else
    0,
#endif
#if defined(TH8_PLATFORM_ANDROID)
    Th8_GetAndroidPlatform,
#else
    0,
#endif
#if defined(TH8_ENABLE_LIBCURL)
    Th8_GetCurlPlatform,
#else
    0,
#endif
    Th8_GetNullIoPlatform,
    Th8_GetLibcPlatform,
    Th8_GetEnvPlatform,
#if defined(TH8_USE_MIMALLOC)
    Th8_GetMimallocPlatform,
#else
    0,
#endif
#if defined(TH8_PLATFORM_COSMOPOLITAN)
    Th8_GetCosmopolitanPlatform,
#else
    0,
#endif
    Th8_GetMemPlatform,
    Th8_UseDefaultPlatform,
#if defined(TH8_ENABLE_FAULT_INJECTION)
    Th8_FaultConfigInit,
#else
    0,
#endif
#if defined(TH8_ENABLE_FAULT_INJECTION)
    Th8_FaultInstall,
#else
    0,
#endif
#if defined(TH8_ENABLE_FAULT_INJECTION)
    Th8_FaultUninstall,
#else
    0,
#endif
#if defined(TH8_ENABLE_FAULT_INJECTION)
    Th8_FaultCtxSize,
#else
    0,
#endif
    Th8_RegisterLanguage,
#if defined(TH8_ENABLE_VARIABLES)
    Th8_ResetSecurityArray,
#else
    0,
#endif
#if defined(TH8_ENABLE_VARIABLES)
    Th8_SaveSystemVar,
#else
    0,
#endif
#if defined(TH8_ENABLE_VARIABLES)
    Th8_RestoreSystemVar,
#else
    0,
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    Th8_AttrFlagsParse,
#else
    0,
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    Th8_AttrFlagsFormat,
#else
    0,
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    Th8_AttrFlagsHave,
#else
    0,
#endif
#if defined(TH8_ENABLE_CRYPTOGRAPHY)
    Th8_AttrFlagsChange,
#else
    0,
#endif
    Th8_SecureZero,
#if defined(TH8_ENABLE_VARIABLES) && defined(TH8_ENABLE_CRYPTOGRAPHY)
    Th8_SecureSetMasterKey,
#else
    0,
#endif
#if defined(TH8_ENABLE_VARIABLES) && defined(TH8_ENABLE_CRYPTOGRAPHY)
    Th8_SecureClearMasterKey,
#else
    0,
#endif
#if defined(TH8_ENABLE_VARIABLES) && defined(TH8_ENABLE_CRYPTOGRAPHY)
    Th8_EnableSecurePersist,
#else
    0,
#endif
#if defined(TH8_ENABLE_VARIABLES) && defined(TH8_ENABLE_CRYPTOGRAPHY)
    Th8_IsSecurePersistEnabled,
#else
    0,
#endif
    Th8_GetCompileOptions,
    Th8_Malloc,
    Th8_Free,
    Th8_Realloc,
    Th8_AttemptMalloc,
    Th8_AttemptRealloc,
    Th8_SafeAlloc,
    Th8_SafeAllocStr,
    Th8_SafeAllocMul,
    Th8_SafeAllocAdd,
    Th8_SafeAllocMulAdd,
    Th8_SafeRealloc,
    Th8_SafeAttemptRealloc,
    Th8_SafeAllocStrAdd,
    Th8_SafeAllocStrMul,
    Th8_SafeAllocMulAdd2,
    Th8_SafeMul,
    Th8_SafeAdd,
#if defined(TH8_ENABLE_LOAD)
    Th8_ListAppendLoaded,
#else
    0,
#endif
#if defined(TH8_BENCHMARKING)
    Th8_GetCacheStats,
#else
    0,
#endif
#if defined(TH8_BENCHMARKING)
    Th8_ResetCacheStats,
#else
    0,
#endif
    Th8_FindInCache,
    Th8_GetLastError,
    Th8_EmitTrace,
    Th8_DoesEnvExist,
    Th8_RegisterPlugin,
    Th8_UnregisterPlugin,
    Th8_ListAppendPlugins,
};
